### ISSUE TITLE
`OpenDialog` doesn't honour the cwd argument if it's missing the trailing slash

### ISSUE THREAD

**Issue by gnif** [aiekick/ImGuiFileDialog#102]
**Describe the bug**

After selecting the file to open/save the path returned by `GetCurrentPath()` does not contain a trailing slash. If this path is used in a future call to `OpenDialog` it will go up one level instead of returning to the path provided.

**To Reproduce**
1. Execute the following code adjusting it to a path that exists:
```cpp
ImGuiFileDialog::Instance()->OpenDialog("dialog", "caption", ".txt", "/home/user");
```
2. Observe the path opened is `/home` and not the path specified.

**Comment by gnif** [comment]
Missed the overloaded call, all good.

**Comment by aiekick** [comment]
:)
