### ISSUE TITLE
Windows 10 path length wrong.

### ISSUE THREAD

**Issue by vmesechkov** [aiekick/ImGuiFileDialog#103]
Can not show real paths because of sensitive NDAs.

For a path like this:
`./testFolder1/testFolder2`
this line
`numchar = GetFullPathNameW(wpath.c_str(), 0, nullptr, nullptr);`
returns 72 chars length for a path with 69 characters, which causes the next two lines to create a broken path string (with 3 spaces at the end).
For example:
`"C:\test\testFolder1\testFolder2   "`
The next call:
`GetFullPathNameW(wpath.c_str(), numchar, (wchar_t*)fpath.data(), nullptr);`
actually returns 69 characters.
The actual path doesn't have special characters or white spaces, its composed of ascii letters and dashes.

I'm using a workaround for the moment at the second call to GetFullPathNameW:
`			numchar = GetFullPathNameW(wpath.c_str(), numchar, (wchar_t*)fpath.data(), nullptr);`
`			if (numchar < fpath.size()) {`
`				fpath.resize(numchar);`
`			}`
which is not the best solution, but I have no time or idea why GetFullPathNameW returns different number of characters for the different calls with the same path. My best guess is it is reserving more space than needed or using somehow the type of the input pointer to determine the needed characters. Maybe trimming could also work, because Windows also trims spaces at the end of a folder name when creating manually.

System is: Asus ROG Strix G17 with Windows 10 x64.
Ubuntu 20.04 works flawlessly, the problem is with the system's API.

Sorry if the formatting is wrong, first comment ever in Github :)

**Comment by aiekick** [comment]
Hello,

Thanks for your feedback.

Will check that tonight, definitly again an issue with windows..

**Comment by aiekick** [comment]
why are you using this shash "/" , on windows in string this is this "\\", maybe this is the reason no ?

and sorry but i doint understand you issue in ImGuiFileDialog ? since the path are converted to use '\\"

**Comment by aiekick** [comment]
It seems your issue is not reltaed to imguifiledialog. You have better chnace on stackoveeflw
