### ISSUE TITLE
Force focus on dialog

### ISSUE THREAD

**Issue by MohammadMDSA** [aiekick/ImGuiFileDialog#107]
Hi. Is there any way that the opened dialog takes focus by force an doesn't give it up until it is closed?

**Comment by aiekick** [comment]
Hello
There is no way to do that in the dialog,
But you can add some imgui stuff for doing that before the call to the display function of imguifiledialog . If i remember you have also a flag for keep a dialog in top, maybe the smar for lock the focus.

**Comment by MohammadMDSA** [comment]
Thank you
