### ISSUE TITLE
scandir results with d_type DT_UNKNOWN not handled correctly.

### ISSUE THREAD

**Issue by EricGriffith** [aiekick/ImGuiFileDialog#109]
**Describe the bug**
I'm using a file system that always returns DT_UNKNOWN for d_type in the results for scandir. This causes the dialog to close unexpectedly when double clicking on a directory to navigate.

**To Reproduce**
1. Open an ImGuiFileDialog to a directory with subdirectories on a file system that returns DT_UNKNOWN for d_type in dirent entries. I'm using a proprietary file system, but am advised that NFS on a Mac M1 may provide similar results.
2. Double click on a subdirectory.
3. The dialog closes instead of navigating to the subdirectory.

**Expected behavior**
The dialog should navigate to the subdirectory.

**Desktop:**
 - OS: Mac M1 Max. macOS version 12.5.1

**Additional context**
The recommended practice is to stat any dirent that has d_type of DT_UNKNOWN.

**Comment by aiekick** [comment]
i tried to force the "end->d_type" to DT_UNKNOWN, but not issue a close

btw if you have directory, so you have all time DT_UNKNOWN.

do you tried std::filesystem by applying c++17 ?

Cna you try to fix this issue, since im not able to reproduce this bug

**Comment by EricGriffith** [comment]
I created a pull request with my local fix.

**Comment by aiekick** [comment]
thanks for the help.

pull request accepted :)
