### ISSUE TITLE
Linux compilation failing

### ISSUE THREAD

**Issue by pierrep** [aiekick/ImGuiFileDialog#11]
**Describe the bug**
I had to add -fpermissive to the build flags in order to get past the first error.
Then I received a second error:
`ImGuiFileDialog.cpp:885:31: error: ‘infos’ was not declared in this scope`

I changed `infos` to `vInfos`
I was then able to build successfully.

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04.4

**Comment by aiekick** [comment]
hello,
exactly, it was fixed some weeks ago.
sorry just seen yout message.
thanks for report the bug
