### ISSUE TITLE
Windows.h not found when OS is case-sensitive

### ISSUE THREAD

**Issue by olivier-omnirobotic** [aiekick/ImGuiFileDialog#111]
When compiling for windows from linux using MinGW, we have a compile error because you are including "Windows.h" with an uppercase "W". 
On Windows platform this does not matter, but in Linux it is case-sensitive and it cannot find Windows.h. 
Changing the include line for "windows.h" all lowercase fixes the issue.

**Comment by aiekick** [comment]
Hello,

ok thanks.

ps : 
if you are using mingw you will have issue with unicode, who is not well supported on window with mingw. 
on window its ok with msvc, but not with mingx and clang as i have tested. so if you would like to display unciode char, uoi will not see them in ImGuiFileDialog
