### ISSUE TITLE
Instantly opens and closes

### ISSUE THREAD

**Issue by krxyt** [aiekick/ImGuiFileDialog#114]
**Describe the bug**
Im using the exact code for the simple dialog inside a "Tab item" button in imgui. If i click it, i just see nothing, but if i spam click it, i can sometimes briefly see it show up for a single frame and then dip.

**To Reproduce**
1. BeginTabBar
2. BeginTabItem
3. Call a function to create a menu for the tab
4. Create a button in that function that begins the dialog when clicked
5. Note that if i put the code outside of the 'tabbar' if statment, it works fine. i just need it to show up where i am trying to have it

**Expected behavior**
A dialog should appear and work as normal

**Screenshots**
I'm sure you can understand my inability to provide screenshots lol

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser firefox
 - Version: latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aiekick** [comment]
Hello,

It seems you are not using the lib in the good way.

You need to call opendialog in any place you want like menubar, tabitem etc. 

And you must call the display function in the main loop with the key you used in opendialog.

If the open dialog is always call zach frme its normal the dialog constantly disapear younneed to call it one timz only xhen you oush a button by ex.

If is what youve done and is always not wroking check the sample app in the master branch and/or show me your code pls

**Comment by aiekick** [comment]
Any news ?
