### ISSUE TITLE
Support for multi layer extension like file.ext1.ext2

### ISSUE THREAD

**Issue by APassbyDreg** [aiekick/ImGuiFileDialog#118]
Current implementation failed to match multi layer extensions like `.ext1.ext2` in filters.

- If I use `.a.b` in the filter, the file won't match because only the last extension is recognized and matched
- If I use regex `(.*\\.a\\.b)` in the filter, the returned path from `GetFilePathName()` will be like `filepath_no_ext.a(.*\\.a\\.b)`

Possible solutions:
- Directly match if the filename ends with filter
- Regex should be handled seperately

Other Issues:
- `IGFD::FileManager::GetResultingFileName` add regex to the end of selected filename directly. This generates error file path.

**Comment by APassbyDreg** [comment]
What I'm trying to have is not a filter with extension `.a` or `.b`, but a filter with extension `.a.b`, which matches files like `file.a.b`. As an example, the `files.associations` setting of vscode can match such files using `"*.a.b": "jsonc"`.

**Comment by aiekick** [comment]
ok thanks for the explain. will working on that feature.

btw, im focused on antoher porject for the moment, so will have some delay

**Comment by jvannugteren** [comment]
This would be great. I could use this feature as well.

**Comment by aiekick** [comment]
can you test now ? i think your issue is fixed

**Comment by jvannugteren** [comment]
Thanks. After a bit of puzzling with the regex I got it to work now.

**Comment by aiekick** [comment]
i spoke to @APassbyDreg who opened this issue :)

**Comment by APassbyDreg** [comment]
Thanks for the fix. It does work well with regex filters, but that needs additional care with the returned `GetFilePathName()` path because it doesn't include the extension as regular filters do. Hopefully, the multi-layer extensions can be treated as regular ones like this:

```
m_fileDialogInstance.OpenDialog( "ChooseFileDlgKey", "Choose File", ".ge.mat,.*", workdir.string().c_str());
```

I managed to work around this by directly checking if the filename ends with the filter in `IsCoveredByFilters` and skipping the replacement if the filename already matched the filter.

**Comment by aiekick** [comment]
Ok cool.

You can check all the covered case where there is no replacepent in the function "ReplaceExtentionWithCurrentFilter" of the filter manager

**Comment by APassbyDreg** [comment]
I'm not sure whether this is a new case or a bug in the existing code, but it seems that this line of code cannot work correctly:

```
m_fileDialogInstance.OpenDialog( "ChooseFileDlgKey", "Choose File", ".ge.mat,.*", workdir.string().c_str());
```

![](https://files.catbox.moe/5ira9j.png)
![](https://files.catbox.moe/cqhql0.png)

The files I want to show are not showing in the dialog with the `.ge.mat` filter.

It seems that currently the `ReplaceExtentionWithCurrentFilter` function does treat the multi-level extension as a regular filter. However, using multi-level extension as regular filter is not working as shown above. That's why I modified the `IsCoveredByFilter` to allow files ending with the filter directly pass the check and show in the dialog.

**Comment by APassbyDreg** [comment]
It seems that the input file extension `vExt` of `IsCoveredByFilter` just recognizes the last extension (which is a result of line 1440 `ImGuiFileDialog.cpp`).  Multi-level extensions are filtered out because they cannot satisfy the `prSelectedFilter.exist(vExt, vIsCaseInsensitive)` condition and thus not shown in the dialog.

**Comment by APassbyDreg** [comment]
This issue changes the previous way to define the _"extension"_ of a file. So there might be a lot of related code to check. That's why I work around it by just adding one simple rule to allow filenames ending with the filter directly pass the check (but this may cause extra problems, I haven't tested it).

**Comment by aiekick** [comment]
Not sure why you say "This issue changes the previous way to define the "extension" of a file". For me we just need to adapt the filtering like i done yesterday with getFilePathName. Or maybe i miss something

**Comment by APassbyDreg** [comment]
As mentioned above, currently the extension of a file is defined to be the characters after the last dot character (line 1440 of `ImGuiFileDialog.cpp`). Under such context, the extension of a file named _file.a.b_ is _b_. However, if multi-level extension is supported (at least, as I expected), the extension of that file should be _a.b_.

If I use ".a.b" as a filter, when judging whether the file _file.a.b_ matches the filter in function `IsCoveredByFilter`, the `vExt` pass to `prSelectedFilter.exist(vExt, vIsCaseInsensitive)` is _b_, but not _a.b_, so the function will return false and filter out  _file.a.b_ from the display.

That's why I say "This issue changes the previous way to define the "extension" of a file". I have come up with two options to fix this:
1. changes the previous way to define the "extension" of a file: that is to say, the definition of extension should be modified to be "any characters after a dot character". This should enable file _file.a.b_ to match with both _.b_ and _.a.b_ filters.
2. take the brutal force design to bypass this problem through directly checking if the filename ends with a filter. However, this need more effort to deal with corner cases like invalid input filter or filename ends with a regex-like string.

**Comment by aiekick** [comment]
im working on a other way. (not commited)

i extract the extention according to the count of dots in the filter extention.

if i have files : toto.a.b, toto.b
with filter ".a.b" we will have files : toto.a.b
with filter .b we will have files : toto.a.b toto.b
with filter .a we will have no files

i apply the same for filter collections but this is failing
with filter {.a.b, .b}
we will have files : toto.a.b only, 
because he use for extraction the max dot per filter of the whole collection. so here 2

and he fail also with filter like .a.*
need to treat specifically the *
maybe fy transform it in a regex

**Comment by aiekick** [comment]
your issue is fixed to me now.
can you confirm ?

**Comment by APassbyDreg** [comment]
The files are correctly shown, but another bug occurs: the filter does not appear in the selection box. Not sure what is causing that.

![](https://files.catbox.moe/v0gj36.png)

notice that the selected filter is empty in the bottom right selection box.

Another problem is that if I enter a file name, the returned path from `GetFilePathName` doesn't include the `.ge.mat` extension, which is inconsistent with the behavior for regular extensions like `.json` etc.

**Comment by aiekick** [comment]
arf, can you show me your opendialog command .

**Comment by APassbyDreg** [comment]
My mistake, I forget to switch back from the regex filter to the plain filter. Currently the `.ge.mat` works well. Instead, it's a bug related to the regex filter. The regex filters are not shown in the filter selection box.

**Comment by aiekick** [comment]
yes when there is a regex i dont know what to do. its not human readable.
one time i renamed "regex", but why that instead of another ? :)
regex have no sense in simple filter.

**Comment by aiekick** [comment]
can we close this isuue ? its ok for you ?

**Comment by jvannugteren** [comment]
The double extensions work now even without regexp. However, I fear you broke the SetFileStyle in the process: 
`ImGuiFileDialog::Instance()->SetFileStyle(IGFD_FileStyleByExtention, ".gif", ImVec4(0.0f, 1.0f, 0.5f, 0.9f), "[GIF]");` I no longer see the coloring (or icon). Not for single extensions nor for double extensions.

**Comment by aiekick** [comment]
thanks. will check that

**Comment by aiekick** [comment]
fixed :) a copy / past mistake :)

**Comment by jvannugteren** [comment]
Hehe. Sounds familiar. Thanks.
