### ISSUE TITLE
Cannot Create Dynamic Library

### ISSUE THREAD

**Issue by fangjunzhou** [aiekick/ImGuiFileDialog#119]
**Describe the bug**

I can only link the library statically for all the modules that use ImGuiFileDialog.

Currently, I create dynamic libraries for most of my modules. But I got a linker error every time I tried to use ImGuiFileDialog as a dynamic library. When I switch the library type from SHARED to STATIC, it compiled successfully.

**To Reproduce**

Create a shared `imgui` library.

Clone the ImGuiFileDialog to external/imguifiledialog.

Create a shared library by adding:

```cmake
file(
    GLOB
    IMGUI_FILE_DIALOG_SRC
    external/imguifiledialog/*.cpp
    external/imguifiledialog/*.h
)
add_library(imgui_file_dialog SHARED ${IMGUI_FILE_DIALOG_SRC})
target_include_directories(
    imgui_file_dialog
    PUBLIC
    external/imguifiledialog
)
target_link_libraries(imgui_file_dialog PUBLIC imgui)
```

Try to link the shared imgui_file_dialog library to other modules and linker will throw `undefined reference to `IGFD::FileDialog::~FileDialog()', `undefined reference to `IGFD::FileDialog::Display(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, ImVec2, ImVec2)'`, `undefined reference to `IGFD::FileDialog::IsOk() const'`, and some other undefined reference linker error.

When changed the library from `SHARED` to `STATIC`, everything works fine. Notice all the libraries using `imgui_file_dialog` also need to change to `STATIC` to link successfully. For example, currently, my main executable uses `frontend`, and `frontend` uses `imgui_file_dialog`. When I only changed the `imgui_file_dialog` to STATIC, some linker errors about `frontend` are thrown, which is really weird.

I think it might be some CMake issue, but all the other libraries do not have this issue. It only happens to ImGuiFileDialog.

**Expected behavior**

All these undefined reference targets should already be compiled to `imgui_file_dialog`

**Desktop (please complete the following information):**
 - OS: Windows
 - Compiler: MinGW32 GCC

**Comment by aiekick** [comment]
Hello,

Yes you cant use it as shared and i will not work on it to do that, 

but you can propose a pull request.

Regards

**Comment by aiekick** [comment]
failed to do it. too many issue with the stl templates.

but you can already use as shared the C Interface. but you will lack the cpp features for sure.
