### ISSUE TITLE
Documentation needed for use as addon, instead of modifying existing project

### ISSUE THREAD

**Issue by connorjak** [aiekick/ImGuiFileDialog#12]
I am attempting to include this library and use it in my application which is running on DirectX11, which is different than the OpenGL that the example application here uses, so I am trying to incorporate the FileDialog code into my app (using Visual Studio 2019, Windows).

I have been having issues. It would be the best if there was documentation on how to add this in to preexisting projects.

**Comment by aiekick** [comment]
Hello,

i have added a little explanation at end in the Readme,
about how you can use ImGuiFileDialog just as a module.

let me Know if its clear for you. its always difficult to be  clear for all :) 

By the way you can also check in this repo who use ImGuiFileDialog as a 
module and customize externaly to it, for have icon instead fo test.

Maybe the way i use is not the best or not the more flexible way for all, 
if you have idea or trick, pleae share) 

i have many things to learn

enjoy :)

**Comment by connorjak** [comment]
That's some good info on the config stuff, thanks!

I managed to get this library working by putting ImGuiFileDialog.cpp, ImGuiFileDialog.h, ImGuiFileDialogConfig.h, and tronkko's dirent.h (from ThirdParty) in one folder. I #included ImGuiFileDialog.h by relative path from my ImGui app's code. I think I also manually did Right Click on Project -> "Add Existing Item" for these four items to get them into my Visual Studio project.

So at least for me, it appears that's all you need to get it working. It would have been good to have these instructions in the README. The ideal case for projects like mine is getting a folder to copy/paste or git submodule and have it work immediately once properly included in the build system.

**Comment by aiekick** [comment]
cool,  happy to help

**Comment by aiekick** [comment]
i finally done what you explain.
there is now a dedicated branch called Lib_Only. :)
