### ISSUE TITLE
How to add a "read-only" check-box?

### ISSUE THREAD

**Issue by rodrigorc** [aiekick/ImGuiFileDialog#122]
I'd like to add a "read-only" check-box to the "Open File" dialog, so that the user can open a file in my program but any "edit" command is disabled.

This is available in many other "Open File" solutions, such as Win32 [1], WinForms [2]:

![image](https://user-images.githubusercontent.com/1128630/218110051-8bcc46d8-f717-426a-8885-aece3b00801f.png)

Some more modern solutions allow adding custom widgets, such as Gtk [3] or Kde [4], that I think they are added just over the buttons:

![image](https://user-images.githubusercontent.com/1128630/218110330-ca55525f-e0d5-443f-a200-c69f718b0a79.png)

Naturally I could just reuse the custom pane, but for a single check-box it will probably not look very nice. If I ever add a "preview" pane, then I could add the read-only check-box at the bottom of the preview and everything would fit nicely. But unfortunately the preview is not ready yet.

Currently, I forked this repo and added a "read-only" flag that creates the check-box at the right of the "Ok/Cancel" buttons. This is how it looks:

![image](https://user-images.githubusercontent.com/1128630/218107680-24c40c4e-2074-467f-8b24-7d128c9e03c2.png)

It will not win any design prize, but I think is good enough for me. Maybe there is a better more generic way to reuse this space to the right of the buttons? Or to reserve a different area similar to the custom pane, but below the list of files instead of to the right?

[1]: https://learn.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-openfilenamea
[2]: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.showreadonly?view=windowsdesktop-7.0
[3]: https://docs.gtk.org/gtk3/iface.FileChooser.html#adding-extra-widgets
[4]: https://api.kde.org/frameworks/kdelibs4support/html/classKFileDialog.html#a08b6053ae3db16cb739bdc42721b15e9

**Comment by aiekick** [comment]
thanks for your time.

yes i think i can have another callback for this space and maybe others, i will study a way for that

**Comment by aiekick** [comment]
why not just override the prDrawFooter funtion for add what you want ?

add a lambda for that make sense

**Comment by rodrigorc** [comment]
@aiekick Sorry for not replying before, I've been somewhat busy... The issue is that my program is written in Rust, so I'm binding the `IGFD_C_API`. And AFAIK, that API does not have an easy way to override a virtual function.

I guess that we could do something like:
```
typedef void (*DrawFooter_t)(ImGuiFileDialog*);
class ImGuiFileDialogC: public ImGuiFileDialog
{
        DrawFooter_t m_virtualDrawFooter;
    protected:
        virtual bool prDrawFooter() {
            ImGuiFileDialog::prDrawFooter();
            if (m_virtualDrawFooter)
                m_virtualDrawFooter(this);
        }
};

IGFD_C_API ImGuiFileDialogC* IGFD_Create(void) { return new ImGuiFileDialogC(); }
IGFD_C_API void IGFD_SetDrawFooterCB(ImGuiFileDialogC *dlg, DrawFooter_t drawFooter) { dlg.m_drawFooter = drawFooter; }
// and so on...
```
I can try that if you think it is worth it.

**Comment by aiekick** [comment]
ok why not.

**Comment by rodrigorc** [comment]
I've just added this commit f8f14868d39169ae42d1e3c2ca325dc4f8a177c7 with an implementation for the footer callback in the C API.

The same can be added for the other callbacks but currently I don't need them. The funny thing is that there are already a few callbacks _and_ a few virtual functions, so your preferred solution may vary.

I would have created a PR, but you have just refactored your branches and rebase to the new DearImGui, so that would take a couple of days...

Please, tell me if you think this is worth merging and I would prepare the PR. Or if you prefer you can just cherry-pick my commit :wink:.

**Comment by aiekick** [comment]
> Well, the only way I know to override a C++ virtual function from a C API is by creating a temporary subclass that forwards the override to a function pointer, the subclass is just an internal artifact. That is a C++ vs C thing, Rust just piggybacks into the C API.

i know. just you propose a possible pr for you overriding. like i said, the overriding is a user side way for customize the dialog.
it make no sense to add your way for this feature in the base lib.  
if you proposed a pr for integrate that feature in IGFD it was different. 
but no worry, the c api will be updated for new features

for your considerations about imgui. i aggree, i checked egui, but the style and the possibilities are far of what imgui can do.
its cool if there is a recent imgui for rust somewhere. (thanks for the info) i studied a way to create a official fork of IGFD fo rust for one of my new app who are in rust.
