### ISSUE TITLE
cant select multi files even though setting the vCountSelectionMax

### ISSUE THREAD

**Issue by SpadeTen** [aiekick/ImGuiFileDialog#124]

**Comment by aiekick** [comment]
You know; No efforts from you will cause no efforts from me...

What version ? Release or current ?
You confirm the issue with the sample app ?

**Comment by SpadeTen** [comment]
I have sovled the problem, the error may be caused by the encoding of my src file. Thanks for your reply

**Comment by aiekick** [comment]
ok good to know.
the encoding concern the content of the file no ? what is the impact for the file to be blocked by the directory scan ?
