### ISSUE TITLE
ImGuiWindowFlags_NoResize does not work for the file dialog.

### ISSUE THREAD

**Issue by gupta-ish** [aiekick/ImGuiFileDialog#126]
I am using the file dialog like this :

`ImGuiFileDialog::Instance()->OpenDialog("ChooseDirDlgKey", "File Dialog", NULL, "../filepath", 1, NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove );
`
The resize option does not disappear from the bottom left of the file dialog. I want my file dialog to be fixed in my imgui window.

**Comment by aiekick** [comment]
Hello,

The imgui flags pmust be passed to the display function. Opendialog use only ImGuiFileDialog flags.

If you have some doubt, you can check the sample app 🤪
