### ISSUE TITLE
Case-insensitive filter group ignores last member

### ISSUE THREAD

**Issue by darktjm** [aiekick/ImGuiFileDialog#128]
E.g. BASIC{.bas,.txt} ignores .txt if case-insensitive file name support is enabled.  The workaround is to just repeat it.
[patch.txt](https://github.com/aiekick/ImGuiFileDialog/files/11684658/patch.txt)

**Comment by aiekick** [comment]
Hello,
It is a regression indeed. 
Will check that tongiht

**Comment by darktjm** [comment]
OK, thanks.  I should've mentioned that the "patch.txt" file is a proposed patch.  I expected github to display text files in-line, but instead it makes it as much of a pain in the ass to view (and upload, for that matter:  it refuses files based on file name patterns) as possible.  Sorry.

I suppose I should file reports for other issues I'm having as well, but I don't really like posting reports without at least a proposed solution.

**Comment by darktjm** [comment]
And the UI is awful as well.  Thus the accidental closing.

**Comment by aiekick** [comment]
you fix is good, it's an oversight of my side when i redesign this function. will add a unit test so

**Comment by aiekick** [comment]
fixed
