### ISSUE TITLE
[newbie question] How to add a button to select the folder not the file?

### ISSUE THREAD

**Issue by moebiussurfing** [aiekick/ImGuiFileDialog#13]
hey @aiekick ,
Thanks for this.
Sorry for this simple question.
I am using this with OpenFrameworks and it works fine.

But how can I add a button to select the current folder/directory?
I don't want to select any file, just the folder.

(I added a button as usual into ImGui but is not showing it...)

**Comment by aiekick** [comment]
hello,

Nice new feature.

You want to have the possibilty to choose directory in more than files or just directory.

In this second case, i can creata a flag for select dir instead of files.

But how can we go on parent directory ?

can you explain more pls ?

**Comment by moebiussurfing** [comment]
could just a button like isOk -> 'setDir'
but without any file selected.
then you can get on "callback" where or the files structure the user was on clicking...

**Comment by aiekick** [comment]
you just need a select Dirrectory Dialog. is that true ?

**Comment by moebiussurfing** [comment]
Yes, thanks!

**Comment by aiekick** [comment]
done.

you just need to call funcs OpenDialog / OpenModal with a filter field at 0
the readme is updated with a gif

Like that, you can select directory wtih one click and open directory with a double click

enjoy
