### ISSUE TITLE
Replacestring gets stuck in infinite loop

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#132]
Hi just a headsup. The master branch doesn't work on Linux for quite some time now due to a very minor mistake. The ReplaceString function gets stuck in an infinite loop if the oldStr and newStr inputs are the same. This happens, probably only in linux, when replacing a "/" in a filepath with also "/". 

I believe the fix is the addition of a simple check at the start of the function:
```
IGFD_API bool IGFD::Utils::ReplaceString(std::string& str, const std::string& oldStr, const std::string& newStr) {
    if(oldStr.compare(newStr)==0)return false; // <- add this check (=
    bool res = false;
    size_t pos = 0;
    bool found = false;
    do {
        pos = str.find(oldStr, pos);
        if (pos != std::string::npos) {
            found = true;
            res   = true;
            str.replace(pos, oldStr.length(), newStr);
            pos += newStr.length();
        } else if (found) { // another loop to be sure there is no other pattern ater replacement
            found = false;
            pos   = 0;
        }
    } while (pos != std::string::npos);
    return res;
}
```

Thanks for having a look at this.

**Comment by JunedKhan101** [comment]
I am willing to submit a PR for this.

**Comment by aiekick** [comment]
hello, 
thanks for your feeedback :)
corrected in the last commit
Bye
