### ISSUE TITLE
MSVC specific pragma directives

### ISSUE THREAD

**Issue by SimonMaracine** [aiekick/ImGuiFileDialog#138]
Tha header file `ImGuiFileDialog.h` contains a lot of `#pragma` directives, that **GCC** compiler complains about:

```
warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
    #pragma warning(disable : 4251)
```
```
warning: ignoring ‘#pragma region IGFD’ [-Wunknown-pragmas]
    #pragma region IGFD LICENSE
```
```
warning: ignoring ‘#pragma endregion ’ [-Wunknown-pragmas]
    #pragma endregion
```

And many, many more, as the header is full of these directives. The problem is that they are **MSVC** specific.

I suggest that you consider removing them, because they can be an annoyance to those using other compilers. And the project is said to be cross platform - well, it is except for this.

I know that their removal might not be desired and that's why want to make it clear that this is only a proposal. Feel free to close this issue, if you don't want to remove them. I won't be mad. :)

**Comment by aiekick** [comment]
Hello,
np i take into account all user advices :)
will check that

**Comment by aiekick** [comment]
its ok now for you ?

**Comment by SimonMaracine** [comment]
One solution would be to add something like this in the `CMakeLists.txt` file of this project:
```
if(UNIX)
    target_compile_options(ImGuiFileDialog PUBLIC "-Wno-unknown-pragmas")
endif()
```

And probably instead of UNIX, it should check for a specific compiler:
`if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")`

**Comment by aiekick** [comment]
ah yes its a solution. i tried "no-unknown-pragmas"' in code and was no effect. but not tested as flags to the compiler.
will test that. i think for unix is enough :)

**Comment by SimonMaracine** [comment]
Maybe it's for the same reason why `#pragma GCC diagnostic ignored "-Wunknown-pragmas"` or `#pragma GCC diagnostic error "-Wunknown-pragmas"` don't work either.

**Comment by aiekick** [comment]
i see some issues and pullrequest on gcc and clang repo about these features, who are full of bug. so one day these pragma ignore in code will work. but for now this can work

**Comment by SimonMaracine** [comment]
I'm warnings free now. :)
Note that `#pragma GCC diagnostic ignored "-Wunknown-pragmas"` is still in the header file. Either there should be written a temporary comment about them, or they should be removed. I suggest the former.

**Comment by aiekick** [comment]
thanks for your help :)
