### ISSUE TITLE
LNK2019 error

### ISSUE THREAD

**Issue by ndrshn** [aiekick/ImGuiFileDialog#14]
Hi,

I just added your module (with your example code) into my imgui glfw example then compiled but it failed with LNK2019 error. Is there any libs that I didn't use ?

here is my code block like in example:

```cpp
if (ImGui::Button("Button"))
{
	igfd::ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Choose Image", ".png\0.jpg\0.bmp\0\0", ".");
	if (igfd::ImGuiFileDialog::Instance()->FileDialog("ChooseFileDlgKey"))
	{
		// action if OK
		if (igfd::ImGuiFileDialog::Instance()->IsOk == true)
		{
			filePathName = igfd::ImGuiFileDialog::Instance()->GetFilepathName();
			filePath = igfd::ImGuiFileDialog::Instance()->GetCurrentPath();
			// action
		}
		// close
		igfd::ImGuiFileDialog::Instance()->CloseDialog("ChooseFileDlgKey");
	}
	bool ret = LoadTextureFromFile(filePath.c_str(), &my_image_texture, &my_image_width, &my_image_height);
	IM_ASSERT(ret);
}        
```

Thanks in advance.

**Comment by aiekick** [comment]
Hello,

do ypu have some extra informations regarding your LNK2019 ? its difficult to guess with no infromations

btw you need dirent lib under windows

your actual code will not work at this moment as expected

in the button you just need to opendialog, but filedialog must be called in render loop

so like that : 
```cpp
if (ImGui::Button("Button"))
{
	igfd::ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Choose Image", ".png\0.jpg\0.bmp\0\0", ".");
}

if (igfd::ImGuiFileDialog::Instance()->FileDialog("ChooseFileDlgKey"))
{
	// action if OK
	if (igfd::ImGuiFileDialog::Instance()->IsOk == true)
	{
		filePathName = igfd::ImGuiFileDialog::Instance()->GetFilepathName();
		filePath = igfd::ImGuiFileDialog::Instance()->GetCurrentPath();
		// action
                bool ret = LoadTextureFromFile(filePath.c_str(), &my_image_texture, &my_image_width,                               &my_image_height);
	        IM_ASSERT(ret);
	}
	// close
	igfd::ImGuiFileDialog::Instance()->CloseDialog("ChooseFileDlgKey");
}
```
dont hesitate to check the main.cpp who contain examples of what you can do and how.

**Comment by ndrshn** [comment]
Sorry for missing description. I included dirent.h but not working :( Here is error output:
![resim](https://user-images.githubusercontent.com/1949598/82155798-227bdc80-9880-11ea-80bb-3ac6c5f8f8ae.png)

**Comment by aiekick** [comment]
is the current app with ImGuiFileDialog work for you ?

**Comment by aiekick** [comment]
any news regarding this issue ?

**Comment by ndrshn** [comment]
Sorry for late reply. Yes, they are linked in my app. If I comment out following line
```c++
igfd::ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Resim Seç", ".png\0.jpg\0.bmp\0\0", ".");
```

file is compiled without error. probably I did something wrong and couldn't fix yet.
I'm gonna try another library, sorry bro :)

**Comment by aiekick** [comment]
ok as you want
