### ISSUE TITLE
ImGuiFileDialogFlags_CaseInsensitiveExtention is broken??

### ISSUE THREAD

**Issue by m9710797** [aiekick/ImGuiFileDialog#140]
Hi,

I _think_ the flag ImGuiFileDialogFlags_CaseInsensitiveExtention is broken.

I'm using this filter:
    `ROM images (*.ri *.rom *.mx1 *.mx2 *.sg){.ri,.rom,.mx1,.mx2,.sg,.gz,.zip},All files (*){.*}`
I'm passing the flag ImGuiFileDialogFlags_CaseInsensitiveExtention to
    `ImGuiFileDialog::Instance()->OpenDialog(...)`
But still only files with an all-lower-case extension show up.

I did some debugging, and I **might** have found the problem.
If I change ImGuiFileDialog.cpp:1415 from
`    if (vMaxLevel > 1 && countExtDot >= vMaxLevel) {`
to
`    if (vMaxLevel >= 1 && countExtDot >= vMaxLevel) {`
then it does behave as I expect.
Bug?

Thanks.

Wouter

**Comment by aiekick** [comment]
Hello, 

thansk fro your feedback. indeed its a bug, we got during the regex filtering implementation i guess.

will fix it, just after adding some related unit tests.

**Comment by aiekick** [comment]
just fixed. thanks again, and sorry :)

**Comment by m9710797** [comment]
No problem. Thanks for looking into this and confirming so quickly!

**Comment by MBilderbeek** [comment]
On a sidenote: https://www.differencebetween.com/difference-between-extension-and-extention/ (TLDR: the correct spelling is Extension, not Extention.)
