### ISSUE TITLE
Show Symlinks

### ISSUE THREAD

**Issue by kfjahnke** [aiekick/ImGuiFileDialog#141]
Hi!
I'm currently browsing the file-select add-ons for Dear ImGui, and your's is tempting! But when I ran a trial, the file-select dialog did not display symlinks. Is this deliberate or am I doing something wrong?

**Comment by aiekick** [comment]
Hello,

sorry i just seen your issue.

just tested and i confirm, this is a bug

**Comment by aiekick** [comment]
fixed. fyi, links are resolved as file or dir in IGFD.

if you have a use caase where you must know if a file or a dir is a link, let me know

**Comment by aiekick** [comment]
compilation fixed.

i understand you use case, and indeed IGFD support links( it was just a bugs), btw my question was about link appearance in IGFD.

there is not any information about what file or dir is a link or not. IGFD check what is behind a link, so he can check file and explore linked directory.

if, in your use cas,e  you need to distinguate what file/dir is a link or a regular file, there is some feature to add

**Comment by aiekick** [comment]
Is it ok for you ? Can Z close thé issue ? 😀

**Comment by kfjahnke** [comment]
Yes, thank you! The bug is gone and compilation works as expected. Symlinks are now displayed and followed correctly.
