### ISSUE TITLE
User providing absolute path to file dialog results in malformed path

### ISSUE THREAD

**Issue by lilggamegenius** [aiekick/ImGuiFileDialog#144]
Currently when providing a path via the dialog, it simply appends the provided path to whatever the currently viewed directory is.
For example, if the dialog is currently viewing `/var/temp` and the user provides a absolute path `/etc/someFile`, the resulting path is `/var/temp/etc/someFile`. 
The best solution to this would be to use something like `std::filesystem`, like with #131 but a passable workaround could be to test if the path provided is valid on its own and to use that instead, otherwise append the current directory like normal.

**Comment by aiekick** [comment]
Hello,

hen you Saïd " when the user provide a path" by what way ? In thé field or in thé édit path widget ?

**Comment by lilggamegenius** [comment]
Inside the field. I also should have mentioned that this only happens when using `GetFilePathName()`.
Most file pickers will see the absolute path and skip appending the current directory, allowing users to simply copy and paste in a path instead of needing to copy/navigate to the parent path and select the file.

For example, using `std::filesystem::path`'s append function exhibits this behavior.

**Comment by lilggamegenius** [comment]
Here are some screenshots to try and better explain the issue

![image](https://github.com/aiekick/ImGuiFileDialog/assets/6175821/0c539663-97a1-4833-9416-c57ac93f7517)
![image](https://github.com/aiekick/ImGuiFileDialog/assets/6175821/c8da032e-fee9-44d8-8a75-8121744e8abd)

**Comment by aiekick** [comment]
Thanks, will check that ronight

**Comment by aiekick** [comment]
so you mean 

if file is existing
  return the file
else 
  return the current dir concatenated with the file 
?

by the way dont use quotes in your path, i not want to support this workaround

**Comment by lilggamegenius** [comment]
Yeah that's right, That will match the behavior of other file dialogs. 
Also the quotes come from Windows's Copy As Path option. It automatically puts them there.

**Comment by aiekick** [comment]
sorry for the delay. its done.

**Comment by lilggamegenius** [comment]
Thanks! Now I won't need to workaround this edge case anymore.
