### ISSUE TITLE
How to configure OpenDialog for "saving as" ?

### ISSUE THREAD

**Issue by Lecrapouille** [aiekick/ImGuiFileDialog#145]
Hi !  Points I did not understand in your README

- In section [Filter Collections](https://github.com/aiekick/ImGuiFileDialog#filter-collections-) and also in the comment of your code source:

```
ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", ICON_IMFDLG_FOLDER_OPEN " Choose a File", filters, ".");
```

ICON_IMFDLG_FOLDER_OPEN is not described and undefined inside your code (if yes where ?) and maybe missing a comma before the `"`.

- In section [Directory Chooser](https://github.com/aiekick/ImGuiFileDialog#directory-chooser-) I'm right if I say that folder != file. So how to configure the code to have a "save as" file with its file extension ? I tried this:

```
    ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey",
                                            "file to save",
                                            nullptr, foobar.filename() + ".json", 1, nullptr,
                                            ImGuiFileDialogFlags_Modal);
```

but the json extension is removed (since folder selection).

- Why not having passed flags SAVE or LOAD like done for modals ?

```
ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Choose File", ".cpp,.h,.hpp", ".");
```

Thanks

**Comment by aiekick** [comment]
hello,

ICON_IMFDLG_FOLDER_OPEN  is just an icon for the imgui font. its jsut an exemple. dont have th le defined  in code.

please check the samples app for uses cases..
