### ISSUE TITLE
Improve Compile Times

### ISSUE THREAD

**Issue by lundmark** [aiekick/ImGuiFileDialog#148]
Hi,

I just started using ImGuiFileDialog, great work on the project!

I did some measurements on my compile times after including it into my project. As I am very keen on making sure that I have fast compile time for fast iterations, I could help but notice that imguifiledialog.cpp takes roughly 750->800 ms to compile on my i9-12900KS. On top of that, any file that includes the ImGuiFileDialog.h increases their compile time by roughly 300 ms where half of that is spent in parsing the header+include files and the rest in code generation (templates). 

As a comparison, the whole of imgui takes about 280 ms to compile and the imgui.h takes 15-20 ms to include. 

There should be multiple simple steps to reduce the compile time, starting by making sure that the correct includes are only done during the right defines (such as <thread> only if USE_THUMBNAILS) are defined. Removing usage of STL would be the biggest gain, specifically regex which takes up about 40% of the time spent in the header. As a comparison, pcre include takes 1.5 ms to include. 

If you are interested in these changes but not doing them I might be able to put some time into it here and there, but generally I think the best result would probably be if done by the author self due to code & style knowledge.

Again, thank you for the great software.

Best,
Simon

**Comment by aiekick** [comment]
Hello,

Thanks for your intérêt.

I have no Time currently to work on that. So if you want you Can propose a pr. By thé way you van also use igfd as a shared lib and a frapper for limite thé incluse impact

Bye
