### ISSUE TITLE
Compile Errors and Warnings in v0.6.6

### ISSUE THREAD

**Issue by goossens** [aiekick/ImGuiFileDialog#150]
When compiling the recent 0.6.6 version using the std::filesystem interface, I get the following problems:

1) ImGuiFileDialog.cpp:441:16: error: use of undeclared identifier 'fs'

This can be fixed by adding "**_namespace fs = std::filesystem;_**" to the _**"IsFileExist"**_ method

2)  warning: delete called on 'IGFD::IFileSystem' that is abstract but has non-virtual destructor

This can be fixed by adding "**_virtual ~IFileSystem() = default;_**" to the "**_IFileSystem_**" class

**Comment by aiekick** [comment]
right, i will fix it

**Comment by aiekick** [comment]
fixed. thanks and sorry
I had an error in the CMakeLists.txt, so the github actions didn't really compile the std::filesystem when requested.
i was surprised why this simple error, but not seen in actions :)

**Comment by goossens** [comment]
Thanks for the fix! Are you going to do an update to release v0.6.6 or do a new release?

**Comment by aiekick** [comment]
yep, i prepare a v0.6.6.1 :) jsut for this mistake :)

**Comment by aiekick** [comment]
Release v0.6.6.1 done

**Comment by goossens** [comment]
Thanks, you are a superstar!

**Comment by aiekick** [comment]
And m'y super power is super mistake 🤣
