### ISSUE TITLE
Files don't show up if they have no file extension

### ISSUE THREAD

**Issue by NothingSpecific** [aiekick/ImGuiFileDialog#161]
In my testing I noticed files without any extension won't show up. This can be a pretty significant problem for *nix-based users, since *nix file handling is far less dependent on file extensions than Windows.

This makes files like `Makefile`s completely invisible to ImGuiFileDialog.

**Comment by aiekick** [comment]
you can use a regex filter. by ex [a-zA-Z0-9]+

**Comment by aiekick** [comment]
use can use some regex filters.

and if you need to Display by Makefiles and some particular extentions, you can mix than in a collection of filters

**Comment by NothingSpecific** [comment]
I was able to get it working with a `((.*))` regex. It's not perfect since the regex shows at the bottom (and it looks slightly weird), but at this point the issue is purely aesthetic.

**Comment by aiekick** [comment]
What do you mean by show at bottom ?

You mean he not respect the alpha order ?

Do you have a screenshot for show why it's weird for you ?

**Comment by NothingSpecific** [comment]
![screenshot](https://github.com/aiekick/ImGuiFileDialog/assets/116540787/f5953e6f-df46-4c26-8aa8-a456a09ad655)

**Comment by aiekick** [comment]
So what ? I only see directories here. No files. It's not related to what you said.

And if you want to explore use cases and customization of igfd you can check the demo app branch  by for know how to display a name instead of the regex in the filter box

**Comment by NothingSpecific** [comment]
So you see the regex being shown at the bottom. That's what I'm referring to. It's not an issue I consider significant. I was planning on ignoring it until I have more relevant aspects of my project worked out.

I'm closing this issue since I'm satisfied with the files showing up at all.

I didn't know there was a way to show custom text instead of the RegEx. I'll look into that, thanks for the suggestion.

**Comment by NothingSpecific** [comment]
The reason it's only showing directories isn't because it's working wrong. I just have a lot of directories. If you scroll down far enough in my home directory you'll eventually come across hundreds of miscellaneous files, all of which ImGuiFileDialog is currently rendering perfectly.

**Comment by aiekick** [comment]
I though you spoke about issue with filtering and display.

The only way and preferred way for show a title instead of a regex is to use a collection filter

**Comment by NothingSpecific** [comment]
I did say there was an issue with filtering and display. You suggested to use a RegEx filter, and that solved the problem.
