### ISSUE TITLE
Issue while scanning directories

### ISSUE THREAD

**Issue by arnaud-neny** [aiekick/ImGuiFileDialog#163]
I have issue on windows while scanning directories (nothing happens). It looks like there is an error in the function **IGFD::FileManager::ScanDir**
line 1934: ScanDirectory is using **vPath** but I think it should be **path**
(tried locally and it's fixing all my issues).

**Comment by aiekick** [comment]
Hello,

yes i think you are right.

will check that tonight

**Comment by aiekick** [comment]
now fixed. thanks. sorry i though i applied you patch before
