### ISSUE TITLE
the file is not selected and does not open

### ISSUE THREAD

**Issue by meth0dLLC** [aiekick/ImGuiFileDialog#174]
After using input text first, I can't select and open the file. Video example - https://youtu.be/mdGCafBqAD0

**Comment by aiekick** [comment]
Hello,

show me the IGFD calling code ?

you can find an example of how to use in the DemoApp branch

**Comment by meth0dLLC** [comment]
1. call IGFD: 
![image](https://github.com/aiekick/ImGuiFileDialog/assets/82164890/c15b9827-46f1-40ce-8b91-ce45aab102c9)
2. I use IGFD to get the path to the file (image). I did not change the IGFD
3. I have an authorization window in the program, where I enter the login code. After entering the code, IGFD does not work correctly and I cannot select a file. If I don't use inputText at the beginning (that is, I don't enter the code), IGFD works fine.

**Comment by aiekick** [comment]
ok strange.

can you show me calling code of your inputText ?

**Comment by meth0dLLC** [comment]
![image](https://github.com/aiekick/ImGuiFileDialog/assets/82164890/ba49d61f-7ef0-45fa-934f-9fb47690d109)
static char bufCode[64] = "\0";

**Comment by aiekick** [comment]
i have 0 idea why there is this issue.
i guess its related to the input text of the footer in IGFD, since its width is broken in you example.
so maybe an issue with ImGui ID's, but difficult to analyse since i have not acces to your app.
maybe you can try to put the display code of IGFD in an another part/scope of your app loop

**Comment by meth0dLLC** [comment]
Okay, thanks for the tip. If I manage to fix the problem, I will write.

**Comment by aiekick** [comment]
thanks. 
just a thing. as i can see, the display code is opened in a begin/end dialog just after yoru ImGui::Button. 

but IGFD will open a dialog too. so its like open a imgui frame in a imgui frame. so maybe cause issues when there is a active id before like with your inputtext.

this is not the good behavior.  

you must put the display code in parallel of any begin/end imgui frame.

**Comment by aiekick** [comment]
any news after my last comment ?
