### ISSUE TITLE
Possible misuse of comma operator here

### ISSUE THREAD

**Issue by metarutaiga** [aiekick/ImGuiFileDialog#178]
Compiler : clang 15.0.0 (clang-1500.3.9.4)

It showed [Possible misuse of comma operator here]

https://github.com/aiekick/ImGuiFileDialog/blob/e39a4bb5c6a01e7873ef522aa6f41497d5c156e9/ImGuiFileDialog.cpp#L1671

**Comment by aiekick** [comment]
ok but this is a valid syntax, and is working perfectly
