### ISSUE TITLE
Not enough GUI backends

### ISSUE THREAD

**Issue by tort-dla-psa** [aiekick/ImGuiFileDialog#18]
For now, there's only GLFW+GLAD+OPENGL support, AFAIK, so it's hard to integrate ImGuiFileDialog into a project that uses something else (SDL2+GLEW+OPENGL in my case)

It would be great if user could decide which backend to use either by providing them as variable in his project which later would be used by cmake in FileDialog build script or by selecting from predefined options.

**Comment by aiekick** [comment]
the gui backend not concern ImGuiFileDialog But dear Imgui himself. 
the example app i propose is at first base on Dear ImGui Sample

so you can check the examples you have with imgui => [backends](https://github.com/ocornut/imgui/tree/master/examples)

**Comment by tort-dla-psa** [comment]
Oh, indeed, I accidently added FileDiaog as subdirectory in my cmake. Now it works
