### ISSUE TITLE
How to set ImGuiFileDialog Window Flags?

### ISSUE THREAD

**Issue by AMRD1234** [aiekick/ImGuiFileDialog#180]
Hello and don't be tired.
Thank you for your wonderful API.
My question is how can I set browser window flags? for example...
ImGuiWindowFlags BrowserWindowFlags = ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;

this is window flags variable...
how to set that when we call :

IGFD::FileDialogConfig _browser_Config;
_browser_Config.path = ".";
_browser_Config.countSelectionMax = 1;
ImGuiFileDialog::Instance()->OpenDialog("Browse_Dialog", "browser", nullptr, _browser_Config);

**Comment by aiekick** [comment]
hello,

thanks.

the imgui windows flags can be passed to igfd when you call the display function.
