### ISSUE TITLE
Icon to filter looks like a search icon (magnifying glass) instead of a filter icon (funnel), which is misleading

### ISSUE THREAD

**Issue by MBilderbeek** [aiekick/ImGuiFileDialog#181]
As the title says. We're using this in the [openMSX project](https://github.com/openMSX/openMSX/) and got some feedback from users. This is one of the issues:

![image](https://github.com/aiekick/ImGuiFileDialog/assets/12675978/26e925bc-0d4f-4048-87ea-e300a2a61716)
The icon is a magnifying glass, which gave users the impression that it is searching, even inside directories. But it's merely a filter for the current list of items in the browser window.

So, I suggest to replace it with a funnel icon by default.

**Comment by MBilderbeek** [comment]
FYI: https://github.com/openMSX/openMSX/commit/27ec4c15d940d62e6996d7cd9728df5580187fca and https://github.com/openMSX/openMSX/commit/6b018a2a6cab2662055805d8d1e22c7b5d90085f

The funnel/filter icon is also available in the font used for the current icons, so it was easy to improve this in our copy.

**Comment by aiekick** [comment]
this is a user side "issue". use the icon you want. i use the icons i want..
