### ISSUE TITLE
Icon to clear the filter is identical to the icon to go to the root directory.

### ISSUE THREAD

**Issue by MBilderbeek** [aiekick/ImGuiFileDialog#182]
As the title says. We're using this in the [openMSX project](https://github.com/openMSX/openMSX/) and got some feedback from users. This is one of the issues: The icon to clear the filter is identical to the icon to go to the root directory. Users found that confusing:
![image](https://github.com/aiekick/ImGuiFileDialog/assets/12675978/3e88b447-74a2-4e31-8f2e-283f2be36394)

**Comment by aiekick** [comment]
Hello,

the icons are not part of IGFD. there are just uised in the DemoApp who is just made for show what can be done.

You can use the icons you want.

**Comment by aiekick** [comment]
and fyi, this icon is for a reset action. so reset to root dir or reset search

**Comment by MBilderbeek** [comment]
> and fyi, this icon is for a reset action. so reset to root dir or reset search

Yes, but a UI with 2 identical buttons with the same icons, but that do different things seems to raise confusion.
