### ISSUE TITLE
File dialog selects file in working directory over selected one

### ISSUE THREAD

**Issue by angryzor** [aiekick/ImGuiFileDialog#184]
When selecting a file with the same name as a file in the running application's current working directory, the check at https://github.com/aiekick/ImGuiFileDialog/blob/16fc5d619ded8798275739a14034357269de71d4/ImGuiFileDialog.cpp#L2587 will naively assume that `filename` is an absolute path, and it will return the file from the application's working directory instead of the actually selected file.

**Comment by aiekick** [comment]
i see.

**Comment by aiekick** [comment]
just fixed
