### ISSUE TITLE
Add support for natural sort algorithm

### ISSUE THREAD

**Issue by lesauxvi** [aiekick/ImGuiFileDialog#186]
Currently, the sort functionality is based on the standard `std::sort` algorithm, which sorts the strings in a pure alphabetical sort order. Natural sort is a variant of the alphabetical order where multi-digit numbers are treated as if they were a single character. It leads to something more human-friendly. This kind of sort algorithm is apparently used in the explorers available on the different OSs to navigate through the files and folders.

It could make sense to add support for natural sorting algorithm (see this [link](https://github.com/scopeInfinity/NaturalSort/) for an example of library).

Is it a good idea and is it complex to add support for alternative sort algorithm?

**Comment by aiekick** [comment]
hello,

no its easy and i could probiee a way for anyone use giys own sorting or integrate as thid party the one header library alphanum i have mirrored on github some years ago

**Comment by lesauxvi** [comment]
Hello,

That would be perfect. Many thanks!

Vincent

**Comment by aiekick** [comment]
in fact Alphanum is not a "one header only" lib. so your proposal is a better choice

**Comment by aiekick** [comment]
I have added the feature. (finally self made and maybe optimizable a bit)
Since its slower than the base sorting, the use is optional.
You can enable it by using the flag ImGuiFileDialogFlags_NaturalSorting

**Comment by lesauxvi** [comment]
Many thanks for you time and reactivity. I just tried the lastest version on a simple test case. I have three files in a folder: *file1.txt*, *file2.txt* and *file11.txt*. 

The standard sort algorithm gives the following order: *file1.txt*, *file11.txt*, *file2.txt*.

The natural sort algorithm that has just been added gives: *file11.txt*, *file1.txt*, *file2.txt*.

My file explorer (Finder) gives: *file1.txt*, *file2.txt*, *file11.txt*.

From what I had in mind and understood, my file explorer gives the correct output as as the number should not be treated digit by digit but as a "whole". 

What do you think?

**Comment by aiekick** [comment]
have you enabled the feature ?

i just tried your test files and this is what i obtain via the DemoApp :
![image](https://github.com/aiekick/ImGuiFileDialog/assets/1434736/9a700cbb-0fd1-4bea-afc3-ca9aef7ac6ac)

**Comment by lesauxvi** [comment]
Yes, this is weird. Anyway, that means that the issue is on my side! Thank you very much for this implementation.

**Comment by aiekick** [comment]
yes maybe but i would like to know what can be the bug.
any particular locales ?
can you tried the DemoApp branch ?

**Comment by lesauxvi** [comment]
No nothing specific. I have not tried yet the DemoApp. I will try that and let you know! Thanks.

**Comment by lesauxvi** [comment]
I did compile the DemoApp and here is what I got :
<img width="470" alt="Capture d’écran 2024-07-07 à 15 35 37" src="https://github.com/aiekick/ImGuiFileDialog/assets/8177167/b9392f0e-6ccf-4faf-8b11-6d83c6d0f770">

That is really weird. Just to make sure, we just have to click on the arrow located on the left of `File name` to sort the content, right?

By the way, to be able to use the DemoApp, I had to change line 67 of the file mainWinLinuxMacOS.cpp from 

```
#if APPLE
```

to 
```
#if __APPLE__
```
otherwise I had the following error message when I tried to execute the application:
```
Glfw Error 65543: NSGL: The targeted version of macOS does not support OpenGL 3.0 or 3.1 but may support 3.2 and above
```

**Comment by aiekick** [comment]
yes just click on the header. even if you dont click the sorting must be ok

thanks for the define

can you enable the tests and run them ?

**Comment by lesauxvi** [comment]
I compiled the tests and run them. Nothing happened and nothing was printed in the terminal (I tried to execute the test from my IDE - CLion - and from the terminal). Is it the attended behavior when everything is fine?

I found a log file whose content is 
```
Start testing: Jul 07 16:44 CEST
----------------------------------------------------------
End testing: Jul 07 16:44 CEST
```

I dive a little bit in the code and I think I do not understand how the tests work. In the *CMakeLists.txt* file of the test folder, there is a line 
```
include_directories("../src")
```
but there is not `src` directory... What am I missing?

**Comment by aiekick** [comment]
you must set the cmake option USE_TEST=ON 

you can check the files im using for github actions in .github/workflows/

and take a one for your compiler

ex for gcc :

mkdir build
cd build 
cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_TEST=ON -DUSE_DIRENT_FILESYSTEM=ON
cmake --build build --config Release
ctest --test-dir build --output-on-failure

**Comment by lesauxvi** [comment]
No, I enabled the test in the main CMakeLists.txt file. I compiled manually (and no longer with my IDE). It worked. You can find the results [here](https://github.com/user-attachments/files/16119836/output_tests.txt). All the tests passed successfully. 

This is really strange! What can I do to help you?

PS : you are welcome and thank you for the wonderful library.

**Comment by aiekick** [comment]
nothing, in my mind, is the tests was passed successfully, so the natural sorting must be ok

**Comment by lesauxvi** [comment]
FYI, I have compiled my code on a windows machine, the DemoApp also and the unit tests. Nothing has changed. This is not working as expected using the DemoApp, but all the tests are OK.

There must be something I do wrong!

**Comment by aiekick** [comment]
there is a but related to the ordering on linux. im investigating..

you have compiled on windows but with a win32 toolchain ?
why was you on mac.. not sure understand.

you have tested on win and mac ?

**Comment by aiekick** [comment]
no finally i have the same result. i just got an exceptions for a particular comparison.

but the sorting is bad in one sense..

in ascending i got test1, test2, test11
but in descending i got test11, test1, test2 but could be test11, test2, test1

will fix that

**Comment by lesauxvi** [comment]
Yes, I tested both on MacOS (my main machine) and on Windows (with a win64 toolchain). I can try on linux if needed (but I'm not sure as you are already doing some tests on linux).

"Happy" to see that you also have an issue ;-).

**Comment by aiekick** [comment]
i have the issue in the dialog but not in the tests with the same file list...

**Comment by lesauxvi** [comment]
It seems to be vicious issue. How can I help you?

**Comment by aiekick** [comment]
nice for you but i always have an issue around :(

**Comment by aiekick** [comment]
i have fix it i guess. 

if you have some time can you test the last build pls ?

**Comment by lesauxvi** [comment]
I just compiled the latest build, and more specifically the DemoApp. Everything runs smoothy and works as expected. All the unit tests passed successfully. 

I think we can conclude that everything is ok and we can close definitely this issue.

Many thanks for your time and efficiency.

**Comment by aiekick** [comment]
yep cool.

many thanks for your time too. 👍
