### ISSUE TITLE
Show ".." entry (and other folders) first

### ISSUE THREAD

**Issue by MBilderbeek** [aiekick/ImGuiFileDialog#188]
This is more intuitive (especially having `..` at the top). 

You can probably take over these commits:
https://github.com/openMSX/openMSX/commit/6a1e8a015183b06139196130e7418e2537276747
and this small bug fix on top of it:
https://github.com/openMSX/openMSX/commit/af558c15a952a99e4ec37e0f96a3b7a1584b42df

The origin of this change was a user saying that this looked very strange:
![image](https://github.com/aiekick/ImGuiFileDialog/assets/12675978/669520e7-1059-4b27-bd11-19a8b62bec9b)

As for keeping all folders together: it helps to make an easier distinction between files and folders. I tried different colors, but this seems to work the best for now.

**Comment by aiekick** [comment]
i never seen the .. in second position in IGFD

how you obtained that ?

**Comment by MBilderbeek** [comment]
Yes, that bug was ours, that's what I meant. I mentioned it so that if you take over the code, you should include that bug fix. That's all.

How you get that? Simply add a folder that starts with a dash `-` as shown in the screenshot.

**Comment by aiekick** [comment]
so its a normal case, by ex you got on a linux :
![image](https://github.com/aiekick/ImGuiFileDialog/assets/1434736/4f5d62e5-50ae-4a8a-8e2a-c7395a71f60a)

**Comment by MBilderbeek** [comment]
I'm just passing on the feedback I got from our users.  They felt the `..` should always be on top, and I think that's good. In fact, when I look in my GNOME native file browser on Linux, it doesn't list `.` and `..` at all. Perhaps that's even better. (The user can already go to a previous folder by clicking on the location bar's parts.)

I also got the feedback that people didn't properly see the difference between files and folders. We solved that by putting the folders on the top. 

In GNOME, folders have a distinct colored icon compared to files. In IGFD, they have different icons, but the difference is subtle (yes, I know the icons could be changed, but I'd rather not reinvent them) and a suggestion was made to use different colors for the icons. Maybe that's an idea for IGFD? Just passing some ideas from our users here...

**Comment by aiekick** [comment]
the .. is appearing for use it when you only are using the dialog without the mouse.

you can use style coloring for distinguish directories from files or many others rules.
you can check the DemoApp branch..

if you have a feature request, please use a separate ticket whell explained with before/after.
So not like the ones you are used to, written on the corner of a table... 
its easy for you to see only your use case, but i need to ensure than all uses case are always valid for any features..

**Comment by aiekick** [comment]
btw i never seen the '-' before the '.'
see : 
![image](https://github.com/aiekick/ImGuiFileDialog/assets/1434736/fd4a6c07-9db2-4451-95aa-0b0a70577fea)
it seems sorting if influenced by locales.
i have other issue regarding sorting between linux and windows. 
and also between me and another user..

**Comment by MBilderbeek** [comment]
FYI, GNOME and Windows Explorer file browsers do not show `..` at all. And in the Windows Command Prompt, the sorting does happen:
![image](https://github.com/user-attachments/assets/688b11ae-1a5d-4e55-82b5-12ac4fbb5083)

**Comment by aiekick** [comment]
like I said before on my windows and my linux the sorting is correct.  - after ..

so your config has maybe some locales who affect this sorting.

**Comment by MBilderbeek** [comment]
Possibly. What about not showing ".." at all, as most file browsers seem to do? It's quite redundant with that path parts section at the top that has directly clickable path sections to go back directories.
