### ISSUE TITLE
For Embedded Dialog Use MinSize Instead of MaxSize argument

### ISSUE THREAD

**Issue by KorespondentAda** [aiekick/ImGuiFileDialog#191]
As stated in [Documentation.md](https://github.com/aiekick/ImGuiFileDialog/blob/master/Documentation.md#embedded-in-other-frames-), if user open embedded IGFD-dialog (with `ImGuiFileDialogFlags_NoDialog` flag set):
> to note, when embedded the ImVec2(0,0) (MinSize) do nothing, only the ImVec2(0,350) (MaxSize) can size the dialog frame

This seems not obvious to me, and using MinSize looks more convenient than MaxSize because:
1. MinSize is third argument, and MaxSize is fourth, so I don't need to specify argument that makes no effect, like I need to pass MinSize now only to pass MaxSize,
2. I wanted to explicitly specify size after seeing that without it dialog is too small to be usable, that give me first think "Need to add constraint for its minimal size". Hovewer, this may be only my specific usecase,
so I suggest swap it.

I looked at code and see no breaks if `vMaxSize` will be changed to `vMinSize` here:
https://github.com/aiekick/ImGuiFileDialog/blob/010cdead252cc84453e896998c69f991e14ecc6f/ImGuiFileDialog.cpp#L3774
But maybe I just don't see it.
Anyway, good job, just want to help it be better.

**Comment by aiekick** [comment]
Hello,

thanks.

so you want a specific stamp for embedded mode ?

**Comment by aiekick** [comment]
?

**Comment by KorespondentAda** [comment]
Sorry for late answer.

Did not understand what you mean by "specific stamp". Can you explain please?
My suggestion is: for embedded mode use `MinSize` to set size of dialog frame.

**Comment by aiekick** [comment]
a specific function stamp..

**Comment by KorespondentAda** [comment]
"Function stamp" like "function signature"? Not an english native, don't know what is it if not signature.
Initially I think about just changing behavior of current `Display` function to use other size argument.
But specifying another function for embedded frame looks good too, maybe even better.

**Comment by aiekick** [comment]
Yes : stamp, footprint, signature. as you want :)

For me use an argument with a wrong name regarding the feature 
is worst than an argument who is doing nothing..

so a specific signature is the solution

**Comment by aiekick** [comment]
Done.
Finally your proposal was the best. 
Did not understood your point of view, until i was inside the code.
sorry :)
