### ISSUE TITLE
Obsolete flag in the latest version of Dear Imgui

### ISSUE THREAD

**Issue by lesauxvi** [aiekick/ImGuiFileDialog#192]
Hello,

I wanted to integrate the lastest dear imgui docking branch (1.91 WIP) in my app to test the new multi-select feature that has just been relseased, and I had a compilation issue. It appears that the flag `ImGuiItemFlags_SelectableDontClosePopup` has been removed in the work-in-progress branch. The flag was still present in the 1.90.9 branch.

See line 878 of `imgui_internals.h`
```
// Obsolete
//ImGuiItemFlags_SelectableDontClosePopup = !ImGuiItemFlags_AutoClosePopups, // Can't have a redirect as we inverted the behavior
```
The flag is used only once in at line 3646 of the file `ImGuiFileDialo.cpp`. The fix should be pretty straighforward.

**Comment by aiekick** [comment]
Hello,

arf. ok i is easy to fix.

he is used in the function m_FlashableSelectable who is a copy past of ImGui::Selectable code just a for have a custom var at line 3624 :
```cpp

    //////////////////////////////////////////////////////////////////
    // this function copy ImGui::Selectable just for this line....
    hovered |= vFlashing;
    //////////////////////////////////////////////////////////////////
```

i not found another way for have the ability to flash on demand a selectable.

so you can just update the code of m_FlashableSelectable and insert again my code at the good location.

**Comment by aiekick** [comment]
fixed

**Comment by lesauxvi** [comment]
Thanks for your reactivity!
