### ISSUE TITLE
Only the first thumbnail is rendered

### ISSUE THREAD

**Issue by tloockx-aim** [aiekick/ImGuiFileDialog#194]
Thanks for creating such an incredible library!

I'm having issues displaying thumbnails. In my case, only the first thumbnail is ever displayed:
![image](https://github.com/user-attachments/assets/c16670ff-a3ab-4ada-8245-1fff5279e56f)

What I think is happening is that the thread running via `m_ThreadThumbnailFileDatasExtractionFunc`  is not waking up anymore after the first time ([code link](https://github.com/aiekick/ImGuiFileDialog/blob/7a94bb1650f6ffa6ea256de365c0846f1020206f/ImGuiFileDialog.cpp#L2882)):

```
    while (m_IsWorking) {
        std::unique_lock<std::mutex> thumbnailFileDatasToGetLock(m_ThumbnailFileDatasToGetMutex);
        // We wait here forever.
        m_ThumbnailFileDatasToGetCv.wait(thumbnailFileDatasToGetLock);
        if (!m_ThumbnailFileDatasToGet.empty()) {
```

The main thread puts all the required file data on the queue in one go and wakes up the thread, but this thread only processes one thumbnail before returning to sleep forever because nobody wakes it up again.

I can _hack_ around this by having a timeout on the wait:

```
    while (m_IsWorking) {
        std::unique_lock<std::mutex> thumbnailFileDatasToGetLock(m_ThumbnailFileDatasToGetMutex);
        // HACK: Wake up to check for thumbnails if nobody will wake us up!
        m_ThumbnailFileDatasToGetCv.wait_for(thumbnailFileDatasToGetLock, std::chrono::milliseconds(50));
        if (!m_ThumbnailFileDatasToGet.empty()) {
```

But I'm pretty sure that's not how you designed it to work.

**Comment by aiekick** [comment]
hello,

thanks for the feedback.

btw i have no issue on my side.

can you try the DemoApp, then do that :

![ImGuiFileDialog_App_Win32_XdzAAE9mhz](https://github.com/user-attachments/assets/c1f1cb9b-d646-4e4e-b72e-15cfb17894a3)

**Comment by tloockx-aim** [comment]
Okay, I verified it on the example application, and it works correct. Then it's time to go and debug my own code. Apologies, and thanks for the help! 

![image](https://github.com/user-attachments/assets/ab9fc109-6a39-4879-a630-4883ce985b0b)

**Comment by aiekick** [comment]
np, its always interesting.

dont hesitate to let me know what was the issue (Thread Concurrency or File loading issue or what else !?), maybe if i can make something easier on my side.
