### ISSUE TITLE
Build fails when IMGUI_HAS_VIEWPORT

### ISSUE THREAD

**Issue by BruceCherniak** [aiekick/ImGuiFileDialog#195]
Code does not build if `IMGUI_HAS_VIEWPORT`,  `flags` is undefined.  I believe you mean to change `flags` to `m_CurrentDisplayedFlags`?

https://github.com/aiekick/ImGuiFileDialog/blob/7a94bb1650f6ffa6ea256de365c0846f1020206f/ImGuiFileDialog.cpp#L3789

https://github.com/aiekick/ImGuiFileDialog/blob/7a94bb1650f6ffa6ea256de365c0846f1020206f/ImGuiFileDialog.cpp#L3786C2-L3797C30
```
#ifdef IMGUI_HAS_VIEWPORT
            // if decoration is enabled we disable the resizing feature of imgui for avoid crash with SDL2 and GLFW3
            if (ImGui::GetIO().ConfigViewportsNoDecoration) {
                flags = vFlags;
            } else {
                auto win = ImGui::GetCurrentWindowRead();
                if (win->Viewport->Idx != 0)
                    flags |= ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar;
                else
                    flags = vFlags;
            }
#endif  // IMGUI_HAS_VIEWPORT
```

**Comment by aiekick** [comment]
arf, yes indeed 

sorry. was a quick changes not fully tested..and i not seen this code portion.

yes your fix is good. will do that tonight or in the afternoon if i got time

**Comment by aiekick** [comment]
fixed
