### ISSUE TITLE
Some files cannot list

### ISSUE THREAD

**Issue by hr2894235132** [aiekick/ImGuiFileDialog#199]
Under Windows, I found that some files cannot be displayed, and some Chinese characters cannot be displayed completely.
eg: "/user/xxx/Download/"

**Comment by aiekick** [comment]
can you try the demoApp ?

**Comment by aiekick** [comment]
any news ?

**Comment by aiekick** [comment]
if you not want to help. i will close this issue

**Comment by hr2894235132** [comment]
> if you not want to help. i will close this issue

Sorry for the late reply, the above problem has been solved by looking at other issues.I have a new problem, when I click on the "Devices" button, it shows me the Dir, but I can't double click on it to get to the decices (eg:[Dir] C:), do you know why?

**Comment by aiekick** [comment]
no i have no idea.

same answer as before, can you test the demoapp ? to be sure than its not a bad use of your side.

**Comment by hr2894235132** [comment]
> > if you not want to help. i will close this issue
> 
> Sorry for the late reply, the above problem has been solved by looking at other issues.I have a new problem, when I click on the "Devices" button, it shows me the Dir, but I can't double click on it to get to the decices (eg:[Dir] C:), do you know why?

I found that the ImGuiFileDialog.cpp file in the master branch doesn't change the value of showDevices, it's always false. shouldn't it be changed in GetDevices()?
![image](https://github.com/user-attachments/assets/65e7c6a6-c38d-4213-a3b0-04397fabe74f)
I modified it here and the above problem was solved.
![image](https://github.com/user-attachments/assets/18cdaa68-cdd6-4107-a7c1-7c47c4cefcf9)

**Comment by aiekick** [comment]
ok good.

will fix that. when i got time

**Comment by aiekick** [comment]
fixed thanks

**Comment by hr2894235132** [comment]
> fixed thanks

nice！
