### ISSUE TITLE
Current path buttons

### ISSUE THREAD

**Issue by dfranx** [aiekick/ImGuiFileDialog#20]
The buttons used to show the current path should have some unique identifier (example: `*itPathDecomp + "##curpath" + std::to_string(index)`).
The lack of such identifier currently causes some buttons not to work, for example when the path is `E:/SHADERed/src/SHADERed` pressing on the latter `SHADERed` button does nothing.

**Info:**
 - OS: Windows 10
 - on latest commit

**Comment by aiekick** [comment]
indeed :) fixed, thanks
