### ISSUE TITLE
Enabling #define USE_EXPLORATION_BY_KEYS throws 'IGFD::FileManager::SelectFileName': function does not take 2 arguments

### ISSUE THREAD

**Issue by moe93** [aiekick/ImGuiFileDialog#200]
I want to allow navigation using the keyboard, so I enabled the ```#define USE_EXPLORATION_BY_KEYS``` flag. However, that causes my code to fail and not compile with the error ```'IGFD::FileManager::SelectFileName': function does not take 2 arguments```.

Within ```bool IGFD::KeyExplorerFeature::m_LocateItem_Loop(FileDialogInternal& vFileDialogInternal, ImWchar vC)```, the function ```SelectFileName``` is called with 2 arguments passed to it, namely, ```fdi.SelectFileName(vFileDialogInternal, infos_ptr);```

However, the SelectFileName function is defines as ```void SelectFileName(const std::shared_ptr<FileInfos>& vInfos)``` in ```ImGuiFileDialog.h```

Thank you

**Comment by aiekick** [comment]
stupid bug fixed. thanks
