### ISSUE TITLE
ApplyFilteringOnFileList when clicking R

### ISSUE THREAD

**Issue by higaski** [aiekick/ImGuiFileDialog#24]
Very minor request for the search reset button labeled "R". I think the behavior when clicking the button should be identical to the one when clearing all characters from the SearchBuffer. This would be a single line fix by adding a call to ApplyFilteringOnFileList after clearing the searchTag:
https://github.com/aiekick/ImGuiFileDialog/blob/72205b3bbf62bc52b4a62a9df345b66c06ebfaf7/ImGuiFileDialog/ImGuiFileDialog.cpp#L897

Also, thank you for this great addition to ImGui.

**Comment by aiekick** [comment]
you are right indded :)
fixed
thanks
