### ISSUE TITLE
igfd::ImGuiFileDialog::Instance(), Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by harderthan** [aiekick/ImGuiFileDialog#27]
**Describe the bug**
`Segmentation fault (core dumped)`, When doing `igfd::ImGuiFileDialog::Instance()`. 

**Expected behavior**
I just followed `Simple Dialog` code for test.
The error was printed when I click the button which described of "Open File Dialog"
 
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version ImGuiFileDialog 0.4v

**Screenshots**
![Screenshot 2020-10-05 22:32:50](https://user-images.githubusercontent.com/13160765/95085875-bdefea00-075a-11eb-9898-99b80499d0ce.png)

**Comment by Maxlisui** [comment]
Hi,

just hit the same problem. After updating from an (very) old version of ImGui.
Has probably something to do when rendering files using `ImGuiListClipper`. See [here](https://github.com/aiekick/ImGuiFileDialog/blob/b989f573cf71254ec90519ac0e572b3bb1458865/ImGuiFileDialog/ImGuiFileDialog.cpp#L998)

`ImGuiListClipper`'s constructor returns `-1` for `DisplayStart`. See [here](https://github.com/ocornut/imgui/blob/e5cb04b132cba94f902beb6186cb58b864777012/imgui.cpp#L2209)

Hope this helps.
