### ISSUE TITLE
Project need to adapt latest imgui tables API

### ISSUE THREAD

**Issue by ice1000** [aiekick/ImGuiFileDialog#33]
When I try to build this project with `USE_IMGUI_TABLES` defined and latest master imgui, some flags are said not to exist. I guess that's because the upstream tables API are renamed, like https://github.com/ocornut/imgui/issues/2957#issuecomment-730633041 (and there are more).

Can we adapt the latest changes? Thanks!

**Comment by ice1000** [comment]
Also, `inline ImGuiListClipper(int items_count, float items_height = -1.0f)` is obsolete. You may consider using `Begin(int items_count, float items_height = -1.0f)` instead.

**Comment by aiekick** [comment]
ok i was not aware of these changes. i will check and correct that tonight :)

**Comment by ice1000** [comment]
Thank you very much!

**Comment by aiekick** [comment]
done
