### ISSUE TITLE
Why is dirent.h included on non-Windows systems?

### ISSUE THREAD

**Issue by ice1000** [aiekick/ImGuiFileDialog#34]
https://github.com/aiekick/ImGuiFileDialog/blob/8bd3f0041267d48f1ccbf7b1c5077f47186a0837/ImGuiFileDialog/ImGuiFileDialog.cpp#L56

This line causes a compilation error on Linux.

**Comment by ice1000** [comment]
I guess I might miss something. I am not familiar with dirent

**Comment by ice1000** [comment]
Well, I guess I may know something now

**Comment by ice1000** [comment]
I know it now. `dirent.h` is already present on non-Windows systems... Sorry for the stupid question.

**Comment by aiekick** [comment]
no problems haha
