### ISSUE TITLE
Compile issue with USE_BOOKMARK not defined

### ISSUE THREAD

**Issue by francoisschelling** [aiekick/ImGuiFileDialog#39]
Got the following error when compiling without USE_BOOKMARK defined:

1>ImGuiFileDialog.cpp
1><...>\Externals\ImGuiFileDialog\ImGuiFileDialog\ImGuiFileDialog.cpp(1008,23): error C2065: 'bookmarksButtonString': undeclared identifier
1><...>\Externals\ImGuiFileDialog\ImGuiFileDialog\ImGuiFileDialog.cpp(1008,47): error C2065: 'm_BookmarkPaneShown': undeclared identifier
1><...>\Externals\ImGuiFileDialog\ImGuiFileDialog\ImGuiFileDialog.cpp(1008,3): error C3861: 'IMGUI_TOGGLE_BUTTON': identifier not found
1><...>\Externals\ImGuiFileDialog\ImGuiFileDialog\ImGuiFileDialog.cpp(1011,22): error C2065: 'bookmarksButtonHelpString': undeclared identifier

To fix it, I've locally put ImGuiFileDialog::DrawBookMark() inside #ifdef USE_BOOKMARK on both the header and source file

**Comment by aiekick** [comment]
ahah yes thanks for the fix.

i will correct. sorry :)

**Comment by francoisschelling** [comment]
Ty!
