### ISSUE TITLE
Windows OS can't display Chinese filename, also can't select those file

### ISSUE THREAD

**Issue by DickyQi** [aiekick/ImGuiFileDialog#45]
OS: Windows 10 Chinese version
ImGui 1.80
ImFileDialog git master
Can NOT display Chinese file name(I already added Chinese fonts, and can show Chinese char will on other interface)
Can NOT select Chinese file name or folder name.

**Comment by aiekick** [comment]
i know there is unicode issue. currently cant show unicode path. there is a way to do it like report in this issue #6
i would like to correct that, but i dont know how to display chinese chars for test since im using the ascii range on my computer

**Comment by aiekick** [comment]
i can convert char to whcar_t and std::string to std::wstring but can be annoying if unicode is not needed.
btw you can display chinese chars in imgui buttons ? because ImGui::Button by ex, use const char* not const whcar_t*
im not familiar, so if you can help, we can convert ImGuiFileDialog for use with unicode

**Comment by truedim** [comment]
I had the same problem on Windows. The following line helps me:
`setlocale(LC_ALL, ".UTF8")`
Do not use wchar_t ))
There are no problems on other platforms (MacOS, Linux, Emscripten)

**Comment by truedim** [comment]
@aiekick - thnak you for the Emscripten patch!
I wonder why you don't accept Windows patch? As far as I understand the modification is completely consistent with dirent.h
I mean that it is better to replace line
```c++
CreateDirectoryA(name.c_str(), nullptr);
```
```c++
size_t n;
std::vector<wchar_t> wn(name.size() + 1);
int error = dirent_mbstowcs_s(&n, wn.data(), wn.size(), name.c_str(), wn.size());
if (error || !CreateDirectoryW(wn.data(), nullptr)) {
	res = false;
}
```
together with setlocale it works like a charm

**Comment by aiekick** [comment]
i not want to refuse path for windows. 
just i dont know how to reproduce the issue. i would like to have the best lib for all cases, but i cant dev like a blinded guy :) 
i can say a thing is solve if i can reproduce it and indeed solve it. 

thanks for your help i will test your proposal :)

**Comment by aiekick** [comment]
i have created a branch [Lib_Only_Unicode_Test](https://github.com/aiekick/ImGuiFileDialog/tree/Lib_Only_Unicode_Test) 
where i have converteds windows functions with your trick
can you test it ?

**Comment by truedim** [comment]
I tested Lib_Only_Unicode_Test and found that it does not work anymore...
The problem is SetCurrentDir function. Also I found tha you replaced the function GetLogicalDriveStringsA with unicode version GetLogicalDriveStringsW - it is not necessary sicnce drive letters are always a-z symbols...
So I suggest to return back the old implemntation of GetDrivesList() and use the following code that works with unicode paths:
```c++
#ifdef WIN32
	inline std::wstring wGetString(const char* str)
	{
		std::wstring ret;
		size_t sz;
		if (!dirent_mbstowcs_s(&sz, nullptr, 0, str, 0))
		{
			ret.resize(sz);
			dirent_mbstowcs_s(nullptr, ret.data(), sz, str, sz - 1);
		}
		return ret;
	}
#endif
	inline bool CreateDirectoryIfNotExist(const std::string& name)
	{
		bool res = false;

		if (!name.empty())
		{
			if (!IsDirectoryExist(name))
			{
#ifdef WIN32
				std::wstring wname = wGetString(name.c_str());
				if (CreateDirectoryW(wname.c_str(), nullptr))
				{
					res = true;
				}
#elif defined(__EMSCRIPTEN__)
				std::string str = std::string("FS.mkdir('") + name + "');";
				emscripten_run_script(str.c_str());
				res = true;
#elif defined(UNIX)
				char buffer[PATH_MAX] = {};
				snprintf(buffer, PATH_MAX, "mkdir -p %s", name.c_str());
				const int dir_err = std::system(buffer);
				if (dir_err != -1)
				{
					res = true;
				}
#endif // defined(UNIX)
				if (!res) {
					std::cout << "Error creating directory " << name << std::endl;
				}
			}
		}

		return res;
	}
	
	
	
	void IGFD::FileDialog::SetCurrentDir(const std::string& vPath)
	{
		std::string path = vPath;
#ifdef WIN32
		if (s_fs_root == path)
			path += PATH_SEP;
#endif // WIN32
		char real_path[PATH_MAX];
		DIR* dir = opendir(path.c_str());
		if (dir == nullptr)
		{
			path = ".";
			dir = opendir(path.c_str());
		}

		if (dir != nullptr)
		{
#ifdef WIN32
			DWORD numchar=0;
//			numchar = GetFullPathNameA(path.c_str(), PATH_MAX, real_path, nullptr);
			std::wstring wpath = wGetString(path.c_str());
			numchar = GetFullPathNameW(wpath.c_str(), 0,nullptr, nullptr);
			std::wstring fpath(numchar,0);
			GetFullPathNameW(wpath.c_str(), numchar, fpath.data(), nullptr);
			int error=dirent_wcstombs_s(nullptr, real_path, PATH_MAX, fpath.c_str(), PATH_MAX - 1);
			if (error)numchar = 0;
			if (!numchar)
			{
				std::cout << "fail to obtain FullPathName " << path << std::endl;
			}
#elif defined(UNIX) // UNIX is LINUX or APPLE
			char* numchar = realpath(path.c_str(), real_path);
#endif // defined(UNIX)
			if (numchar != 0)
			{
				m_CurrentPath = real_path;
				if (m_CurrentPath[m_CurrentPath.size() - 1] == PATH_SEP)
				{
					m_CurrentPath = m_CurrentPath.substr(0, m_CurrentPath.size() - 1);
				}
				SetBuffer(InputPathBuffer, MAX_PATH_BUFFER_SIZE, m_CurrentPath);
				m_CurrentPath_Decomposition = splitStringToVector(m_CurrentPath, PATH_SEP, false);
#if defined(UNIX) // UNIX is LINUX or APPLE
				m_CurrentPath_Decomposition.insert(m_CurrentPath_Decomposition.begin(), std::string(1u, PATH_SEP));
#endif // defined(UNIX)
				if (!m_CurrentPath_Decomposition.empty())
				{
#ifdef WIN32
					s_fs_root = m_CurrentPath_Decomposition[0];
#endif // WIN32
				}
			}

			closedir(dir);
		}
	}

```

**Comment by aiekick** [comment]
drives are always A-Z letter ?. a chinese guy cant define a other char ?

**Comment by truedim** [comment]
> drives are always A-Z letter ?. a chinese guy cant define a other char ?

Yes.
There are some discussion about it, for example:
[Windows drive letters for non-Latin languages](https://superuser.com/questions/384875/windows-drive-letters-for-non-latin-languages)
[How to map a drive when you run out of letters?](https://arstechnica.com/civis/viewtopic.php?t=824363)

**Comment by aiekick** [comment]
is there any issues to switch on c++17 for using std::filesystem instead of dirent.
maybe in some rare case, std::filesystem is not available correctly for some FS or systems ?

**Comment by aiekick** [comment]
@DickyQi, can you test the new version. i think he resolve your issue. thans to the great help of @truedim

**Comment by Trzeth** [comment]
@aiekick  It still doesn't work on Chinese environment.

In `IGFD::FileDialog::SetCurrentDir` => `int error = dirent_wcstombs_s(nullptr, real_path, PATH_MAX, fpath.c_str(), PATH_MAX - 1)`
return EILSEQ until set `_wsetlocale(LC_ALL, L"")` ahead

And have to encoding filename(and path dir) to utf-8 when set to ImGui Text

Function below works fine.

Thanks for previous work!

```C++

	void IGFD::FileDialog::DrawPathComposer()
	{
		if (IMGUI_BUTTON(resetButtonString))
		{
			SetPath(".");
		}
		if (ImGui::IsItemHovered())
			ImGui::SetTooltip(buttonResetPathString);

#ifdef WIN32
		ImGui::SameLine();

		if (IMGUI_BUTTON(drivesButtonString))
		{
			m_DrivesClicked = true;
		}
		if (ImGui::IsItemHovered())
			ImGui::SetTooltip(buttonDriveString);
#endif // WIN32

		ImGui::SameLine();

		ImGui::SeparatorEx(ImGuiSeparatorFlags_Vertical);

		// show current path
		if (!m_CurrentPath_Decomposition.empty())
		{
			ImGui::SameLine();

			if (m_InputPathActivated)
			{
				ImGui::PushItemWidth(ImGui::GetContentRegionAvail().x);
				ImGui::InputText("##pathedition", InputPathBuffer, MAX_PATH_BUFFER_SIZE);
				ImGui::PopItemWidth();
			}
			else
			{
				int _id = 0;
				for (auto itPathDecomp = m_CurrentPath_Decomposition.begin();
					itPathDecomp != m_CurrentPath_Decomposition.end(); ++itPathDecomp)
				{
					if (itPathDecomp != m_CurrentPath_Decomposition.begin())
						ImGui::SameLine();
					ImGui::PushID(_id++);

					std::wstring wstr = wGetString((*itPathDecomp).c_str());

					int nLen = WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, NULL, NULL, NULL, NULL);
					char* pBuf = new char[nLen + 1];
					WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), nLen, pBuf, nLen, NULL, NULL);

					bool click = IMGUI_PATH_BUTTON(pBuf);
					delete[] pBuf;

					ImGui::PopID();
					if (click)
					{
						m_CurrentPath = ComposeNewPath(itPathDecomp);
						m_PathClicked = true;
						break;
					}
					// activate input for path
					if (ImGui::IsItemClicked(ImGuiMouseButton_Right))
					{
						SetBuffer(InputPathBuffer, MAX_PATH_BUFFER_SIZE, ComposeNewPath(itPathDecomp));
						m_InputPathActivated = true;
						break;
					}
				}
			}
		}
	}

//The same convert in void IGFD::FileDialog::DrawFileListView(ImVec2 vSize)

	void IGFD::FileDialog::SetCurrentDir(const std::string& vPath)
	{
		std::string path = vPath;
#ifdef WIN32
		if (s_fs_root == path)
			path += PATH_SEP;
#endif // WIN32
		char real_path[PATH_MAX];
		DIR* dir = opendir(path.c_str());
		if (dir == nullptr)
		{
			path = ".";
			dir = opendir(path.c_str());
		}

		if (dir != nullptr)
		{
#ifdef WIN32
			DWORD numchar = 0;
			//			numchar = GetFullPathNameA(path.c_str(), PATH_MAX, real_path, nullptr);
			std::wstring wpath = wGetString(path.c_str());
			numchar = GetFullPathNameW(wpath.c_str(), 0, nullptr, nullptr);
			std::wstring fpath(numchar, 0);
			GetFullPathNameW(wpath.c_str(), numchar, (wchar_t*)fpath.data(), nullptr);

			_wsetlocale(LC_ALL, L"");
			int error = dirent_wcstombs_s(nullptr, real_path, PATH_MAX, fpath.c_str(), PATH_MAX - 1);
			if (error)numchar = 0;
			if (!numchar)
			{
				std::cout << "fail to obtain FullPathName " << path << std::endl;
			}
#elif defined(UNIX) // UNIX is LINUX or APPLE
			char* numchar = realpath(path.c_str(), real_path);
#endif // defined(UNIX)
			if (numchar != 0)
			{
				m_CurrentPath = real_path;
				if (m_CurrentPath[m_CurrentPath.size() - 1] == PATH_SEP)
				{
					m_CurrentPath = m_CurrentPath.substr(0, m_CurrentPath.size() - 1);
				}
				SetBuffer(InputPathBuffer, MAX_PATH_BUFFER_SIZE, m_CurrentPath);
				m_CurrentPath_Decomposition = splitStringToVector(m_CurrentPath, PATH_SEP, false);
#if defined(UNIX) // UNIX is LINUX or APPLE
				m_CurrentPath_Decomposition.insert(m_CurrentPath_Decomposition.begin(), std::string(1u, PATH_SEP));
#endif // defined(UNIX)
				if (!m_CurrentPath_Decomposition.empty())
				{
#ifdef WIN32
					s_fs_root = m_CurrentPath_Decomposition[0];
#endif // WIN32
				}
			}

			closedir(dir);
		}
	}
```

**Comment by aiekick** [comment]
hello,
thanks for the feedback.
but you think its better to define locale in ImGuiFileDialog instead of in app ?
what append if an app use another locale than LC_ALL ?

**Comment by Trzeth** [comment]
> I had the same problem on Windows. The following line helps me:
> `setlocale(LC_ALL, ".UTF8")`
> Do not use wchar_t ))
> There are no problems on other platforms (MacOS, Linux, Emscripten)

I test it again and find just need to set `_wsetlocale(LC_ALL, L".UTF8")` and nothing need to do more.

Maybe you're right.
But I still think the filepath should be saved as utf8. For lots of convience.
So maybe just need to use `MultiByteToWideChar` to get ride the global variable?

**Comment by aiekick** [comment]
in the sample app i do "setlocale(LC_ALL, ".UTF8");" in fist line of main function.
i think a user who must work with unicode know how to do and must apply locale on his app.
im not sure if it is the goal of this library to do that in place of the user.

maybe i can just popose a define with the locale format. and a commented define will not define the locale in place fo the user.
can be a good compromise

**Comment by Trzeth** [comment]
You're right. Thanks.

**Comment by DickyQi** [comment]
I have modified a version which is using new dirent.h. I tested on Chinese version Windows10. Anyone help to test it, please.
[ImGuiFileDialog_win32_UTF8.patch.txt](https://github.com/aiekick/ImGuiFileDialog/files/6269009/ImGuiFileDialog_win32_UTF8.patch.txt)

**Comment by aiekick** [comment]
thanks for this patch, i will

**Comment by DickyQi** [comment]
@aiekick I am using different porting of dirent for windows,  dirent header file has description.

**Comment by aiekick** [comment]
ok but why theses modifications. as i know there is no more issue in unicode when you define the good setlocale

**Comment by aiekick** [comment]
hello there,

i have finally created an implementation with std::filesystem (c++17) of the new ImGuiFileDialog

you just need to use this define in the config file

#define USE_STD_FILESYSTEM

you can test that in the branch : https://github.com/aiekick/ImGuiFileDialog/tree/Lib_Only_Std__FileSystem_WIP

as i know the unicode is fully supported now, ( just fixed a bug in the path composer)
