### ISSUE TITLE
 Support installation from vcpkg

### ISSUE THREAD

**Issue by weijen6** [aiekick/ImGuiFileDialog#47]
I used the sample code in vs2019, but got multiple errors, , I don’t know which steps I did wrong...

	if (ImGui::Button("Open File Dialog"))
		ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Choose File", ".cpp,.h,.hpp", ".");
	if (ImGuiFileDialog::Instance()->Display("ChooseFileDlgKey"))
	{
		if (ImGuiFileDialog::Instance()->IsOk())
		{
			std::string filePathName = ImGuiFileDialog::Instance()->GetFilePathName();
			std::string filePath = ImGuiFileDialog::Instance()->GetCurrentPath();
		}
		ImGuiFileDialog::Instance()->Close();
	}

1>main.obj : error LNK2019: 在函式 "public: __thiscall IGFD::FileDialog::FileDialog(void)" (??0FileDialog@IGFD@@QAE@XZ)"public: static class IGFD::FileDialog * __cdecl IGFD::FileDialog::Instance(void)" (?Instance@FileDialog@IGFD@@SAPAV12@XZ) 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: void __thiscall IGFD::FileDialog::OpenDialog(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int const &,void *,int)" (?OpenDialog@FileDialog@IGFD@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0PBD0ABHPAXH@Z)_main 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: bool __thiscall IGFD::FileDialog::Display(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,struct ImVec2,struct ImVec2)" (?Display@FileDialog@IGFD@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HUImVec2@@1@Z)_main 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: void __thiscall IGFD::FileDialog::Close(void)" (?Close@FileDialog@IGFD@@QAEXXZ)_main 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: bool __thiscall IGFD::FileDialog::IsOk(void)" (?IsOk@FileDialog@IGFD@@QAE_NXZ)_main 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall IGFD::FileDialog::GetFilePathName(void)" (?GetFilePathName@FileDialog@IGFD@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)_main 中參考了無法解析的外部符號
1>main.obj : error LNK2019: 在函式 "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall IGFD::FileDialog::GetCurrentPath(void)" (?GetCurrentPath@FileDialog@IGFD@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)_main 中參考了無法解析的外部符號
1>C:\Users\weijen\source\repos\PainterWithGUI\Debug\PainterWithGUI.exe : fatal error LNK1120: 7 個無法解析的外部符號

**Comment by aiekick** [comment]
is seem not to be an issue with ImGuiFileDialog, just a c++ issue.
like forgot to add the cpp file of ImGuiFileDialog in your project or something.
you can compare you way with the app you have in the brtanch master :)

**Comment by weijen6** [comment]
Sorry, How do I add ImGui FileDialog.cpp to the project in vs2019?

> is seem not to be an issue with ImGuiFileDialog, just a c++ issue.
> like forgot to add the cpp file of ImGuiFileDialog in your project or something.
> you can compare you way with the app you have in the brtanch master :)
> what is the relation with vcpkg ?

**Comment by aiekick** [comment]
Heu i have no time for this kind of questions.
if you dont know how to solve this situation, the best way for you is to search help on a dedicated c++ forum.
