### ISSUE TITLE
How not to show the hidden file ?

### ISSUE THREAD

**Issue by Corezcy** [aiekick/ImGuiFileDialog#51]
**Describe**
How not to show the hidden file started with `.`, such as `.git` ? Only use the filters ?

**Comment by aiekick** [comment]
good question haha :)

i will add an option for hide them

**Comment by Corezcy** [comment]
> good question haha :)
> 
> i will add an option for hide them

waiting for you

**Comment by aiekick** [comment]
done. 
you can prevent display of hidden files by using the flag ImGuiFileDialogFlags_DontShowHiddenFiles
in OpenModal or OpenDialog call

**Comment by Corezcy** [comment]
Thanks a lot ! So timely !
