### ISSUE TITLE
Using the latest version cannot see directories without setting filters 

### ISSUE THREAD

**Issue by Corezcy** [aiekick/ImGuiFileDialog#52]
**Describe the bug**
Using the latest version containing `ImGuiFileDialogFlags_DontShowHiddenFiles`, when I set ImGuiFileDialog as this(want to see directories in current path):
```cpp
    ImGuiFileDialog::Instance()->OpenDialog(
        "ChooseScenDownloadPath", "Choose Scenario Download Path", nullptr, ".",
        "", 1, nullptr, ImGuiFileDialogFlags_DontShowHiddenFiles);
```
But I get this
![image](https://user-images.githubusercontent.com/33271784/111957684-4b67a080-8b27-11eb-91b6-d8b8d1d29074.png)

I cannot see directories when changing  path. In last version which have not added the
`ImGuiFileDialogFlags_DontShowHiddenFiles`, it works.

I can see directories only if set the filters.(eg. set the filters `.json,.txt`)
![image](https://user-images.githubusercontent.com/33271784/111957941-9e415800-8b27-11eb-9154-c6887ff11a91.png)

**Desktop (please complete the following information):**
 - OS: Linux zcy-omen 5.4.0-58-generic #64~18.04.1-Ubuntu

**Comment by Corezcy** [comment]
In last version, it sees like this:
![image](https://user-images.githubusercontent.com/33271784/111960830-342ab200-8b2b-11eb-8aa1-491046de0390.png)

**Comment by Corezcy** [comment]
when I  read your commit and  comment this line
https://github.com/aiekick/ImGuiFileDialog/blob/5e22ceb925ab34cf47437c16b80037ec831c38a8/ImGuiFileDialog.cpp#L2159
it works again. But I dont know whether there are any other problems ?

**Comment by aiekick** [comment]
thanks for the report. i will check, im sure i missed somethings :)

**Comment by Corezcy** [comment]
> thanks for the report. i will check, im sure i missed somethings :)
> 
> what is the vertical line you have on the pictures ?

The horizontal line is the coordinate system rendering.

**Comment by Corezcy** [comment]
Waiting for your good news

**Comment by aiekick** [comment]
sorry for the late reply. its ok know i think.
in directory mode we must have the ability to select the current dir, and just in this mode we must show the dir "."
this condition (you pointed before) was indeed the bug and is now fixed as i know.
its ok for you or you see other bug ?
thanks :)

**Comment by Corezcy** [comment]
> sorry for the late reply. its ok now i think.
> in directory mode we must have the ability to select the current dir, and just in this mode we must show the dir "."
> this condition (you pointed before) was indeed the bug and is now fixed as i know.
> its ok for you or you see other bug ?
> thanks :)

I will download the latest and try ! Very nice and  thanks a lot !
