### ISSUE TITLE
Problem with OVERWRITE DIALOG

### ISSUE THREAD

**Issue by ClaudeLx** [aiekick/ImGuiFileDialog#53]
In the function
bool IGFD::FileDialog::Confirm_Or_OpenOverWriteFileDialog_IfNeeded(bool vLastAction, ImGuiWindowFlags vFlags)
GetFilePathName is used to get the file name.	
As you know GetFilePathName always return current file with selected extension,
making the test to see if the file already exists, return an incorrect result.
Thanks.

**Comment by aiekick** [comment]
indeed your are right.
thanks for the feedback :)

**Comment by aiekick** [comment]
heu im not sure finally. i was tired yesterday haha

when you create a file you need to be sure than the final file, so the file name + the current selected filter (returned by GetFilePathName ) already exist or not no ?

so why using GetFilePathName() is a problem ?

what is you use case ?

**Comment by ClaudeLx** [comment]
I see 2 cases. With * filter selected:

1) you type the entire file name including
  the extension and click OK.
2) you select an existing file, modify the name
 slightly or not, and click OK.

**Comment by aiekick** [comment]
ok so yes with a filter "*" or ".*" there is a problem
thanks

**Comment by aiekick** [comment]
sorry, s busy. with this fix he will work i guess. can you check ?

**Comment by ClaudeLx** [comment]
Would like to,but need a few days before I am able to.

**Comment by ClaudeLx** [comment]
Problem is corrected,but something else is broken.
1)If you type a non existing file name and click OK
ImGuiFileDialog::Instance()->GetSelection()
returns nothing.
2)If you type an existing file name,
the overwrite dialog appears.
If you click confirm
it returns the file name.
3)If you type a non existing file name and click OK,
it returns the existing file name of case 2.

I don't know what corrections you made,but I'm wondering
if it wouldn't be easier to use GetSelection instead
of GetFilePathName in the function
Confirm_Or_OpenOverWriteFileDialog_IfNeeded.
Only a suggestion.

**Comment by aiekick** [comment]
1) its normal. GetSelection() return what is selected (so only existing files). GetFilePathName() return what is wrote in the input field + many treatment according to filters
2) ok
3) its a bug

GetSelection was made when you have to deal with more than 1 selected files
Maybe i can rename GetFilePathName GetInputField or seomthing.

GetSelection must be used only when you want to have a select file/directory dialog

for the other cases you must use GetFilePathName, and one file at a time

**Comment by ClaudeLx** [comment]
OK I get it. I'll use GetSelection to open files
and GetFilePathName to save a file.
Thanks.

**Comment by aiekick** [comment]
thanks for your time and your help btw :)
i will try to better explain the api on the readme.md.
and there is a bug you discovered to correct.
