### ISSUE TITLE
Use <filesystem> with std::filesystem::path

### ISSUE THREAD

**Issue by phcerdan** [aiekick/ImGuiFileDialog#54]
First of all, thanks for maintaining this great widget!

What do you think about using C++17 and the header <filesystem> to simplify all the path and filename logic.
Using the `std` makes it easier to be multi-platform at the cost of needing a relatively modern compiler.

A random example:
```cpp
	inline PathStruct ParsePathFileName(const std::string& vPathFileName)
	{
		PathStruct res;

		if (!vPathFileName.empty())
		{
			std::string pfn = vPathFileName;
			std::string separator(1u, PATH_SEP);
			replaceString(pfn, "\\", separator);
			replaceString(pfn, "/", separator);

			size_t lastSlash = pfn.find_last_of(separator);
			if (lastSlash != std::string::npos)
			{
				res.name = pfn.substr(lastSlash + 1);
				res.path = pfn.substr(0, lastSlash);
				res.isOk = true;
			}

			size_t lastPoint = pfn.find_last_of('.');
			if (lastPoint != std::string::npos)
			{
				if (!res.isOk)
				{
					res.name = pfn;
					res.isOk = true;
				}
				res.ext = pfn.substr(lastPoint + 1);
				replaceString(res.name, "." + res.ext, "");
			}
		}
		return res;
	}

```
```cpp
#include <filesystem>

inline PathStruct ParsePathFileName(const std::string& vPathFileName)
{
  namespace fs = std::filesystem;
  PathStruct res;
  if (vPathFileName.empty())
    return res;

  auto fsPath = fs::path(vPathFileName);

  if(fs::is_regular_file(fsPath)) {
    res.name = fsPath.string();
    res.path = fsPath.parent_path().string();
    res.ok = true;
  } // else if fs::is_directory?

  return res;
}
```

**Describe the solution you'd like**
Use c++17 <filesystem> and replace all the in-house string substitution code.

**Comment by aiekick** [comment]
you are not the first one who propose to use c++17.
but if i do that this widget will be less used because not all project are targeting c++17, the most is c++11 mini.
and i have no time to build this lib for use c++17 as im suing c++1 in my porjects.
but if you can please propose a PR (with unicode support) and i could keep the both way's available by "#define"

**Comment by phcerdan** [comment]
I completely understand, I had to try :P

**Comment by aiekick** [comment]
hello,

i have finally created an implementation with std::filesystem (c++17) of the new ImGuiFileDialog

you jsut need to use this define in the config file

#define USE_STD_FILESYSTEM

you can test that in the branch : https://github.com/aiekick/ImGuiFileDialog/tree/Lib_Only_Std__FileSystem_WIP

**Comment by aiekick** [comment]
Hello,
i have added a FileSystem interface. you can now use your own FileSystem.
check the DemoApp who show how to use this feature with bool::filesystem
