### ISSUE TITLE
Provide option to disable Create Directory

### ISSUE THREAD

**Issue by phcerdan** [aiekick/ImGuiFileDialog#55]
I know that read/write operations share the same dialog, I wonder if it would be possible to disable the "Create Directory" `DrawDirectoryCreation()` in `DrawHeader()`at runtime.

Maybe passing `vFlags` to `DrawHeader`?

It doesn't fit to have the option to create a folder when opening a file IMO.

**Comment by aiekick** [comment]
yes indeed. => to do

**Comment by aiekick** [comment]
its done in the alst commit. sorry for the delay
