### ISSUE TITLE
Error when using USE_EXPLORATION_BY_KEYS

### ISSUE THREAD

**Issue by Akshat-max-dev** [aiekick/ImGuiFileDialog#57]
Line 627 in ImGuiFileDialog.cpp
Function 'SetNavID' is missing the 4th argument.

**Comment by aiekick** [comment]
i know, you can comment SetNavID. no need here

**Comment by Akshat-max-dev** [comment]
ok

**Comment by aiekick** [comment]
this section will be refactored. im working on an improvment, and i partially rewrote the class for the thumbnail feature

**Comment by aiekick** [comment]
you can keep it opened no problem. its a remainder for me to correct it.
in more, im a bit busy for the moment

**Comment by aiekick** [comment]
it seem i commited in 86befe1883b40ee6b3b9b5ca8499ef4052f2c813
not remembered haha
