### ISSUE TITLE
Issue: Question - Supported Platforms?

### ISSUE THREAD

**Issue by crispyi2** [aiekick/ImGuiFileDialog#60]
# explanation
So im making a rythm game ind im planning on having inbuilt modding tools that are made using linux I need it to work on all platforms including: emscripten - ✅ which I have as the default way to build the game, windows - ❌ wich i havent gotten working since I dont have a windows 10 pc, macOS - ❌  i dont expect this one to happen anytime soon if it isnt already done cuz apple makes developing harder than it needs to be, and linux - ✅ Linux is the only other build option i could use so yeah.

# Wich ones are supported

Info would be appreciated

# Im an open source newbie

sorry for any bad markdown formatting I havent quite got the hang of being an open source gamedev, lol

**Comment by aiekick** [comment]
ImGuiFileDialog is based on the framework "Dear imGui" and use dirent.h of files operations. 
so if ImGui is working in you system and dirent.h is available, the lib can work without issues.

dirent.h is available on all unix like system as i know, 
and a special version is included in the Lib_Only direcotry for get ImGuiFileDialog working on windows.

so for me the minimals systems who are supported's are : Win, Linux, Osx.

If you have imgui working with other system i guees this lib will work too.
If you not have imgui, the lib will not..

**Comment by crispyi2** [comment]
thx for letting me know.
sorry for the slow reply

**Comment by aiekick** [comment]
np
