### ISSUE TITLE
Items Dissapear after Mouse Release

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#61]
Many thanks for making  and sharing this library it has been very useful for my project.

After the introduction of double clicking a couple of months ago noticed a graphical glitch. When single clicking an item in the list, after the mouse is released, the remaining items on the list are not rendered for one frame. It is not random and always happens. I managed to capture some screenshots by making a movie. 

What it looks like before mouse release:
![image](https://user-images.githubusercontent.com/78733220/121325752-2870af80-c912-11eb-9777-f9d47153f6cf.png)

One frame after releasing the mouse:
![image](https://user-images.githubusercontent.com/78733220/121325806-36263500-c912-11eb-914f-237d9ed5d98c.png)

Then everything goes back to normal.

Thanks for looking at this

**Comment by aiekick** [comment]
Hello,

thanks for reported this.

btw not sure if in understand well.

you say, when you double click for open a directory, the frame after, the end of the list is not rendered ?

if this is that its normal.
When you open the dir, ImGuiFileDialog will start to scan the new directory and so empty the current list.
and its happenning during the display, so for avoid unecessary extra code, i decided to break the loop.
so as weel the end of the list is not rendered the next frame, but only the next frame.

is this a problem for you ?

**Comment by jvannugteren** [comment]
Ok that explains indeed why it happens. It is a problem though, because when I do only a single click (not opening the next directory/file) it also happens. This causes the itemlist to look glitchy every time you click an item.

**Comment by jvannugteren** [comment]
After your explanation I figured out that it could be avoided by commenting out line #1519 `return true; // needToBreakTheloop`. I don't know if this causes other issues?

**Comment by aiekick** [comment]
so the problem for you is the glitch.

**Comment by jvannugteren** [comment]
Yes it is only visual. But gets annoying quickly. I can make a merge request of my tiny modification if you like?

**Comment by aiekick** [comment]
if you want. but i not made that just like that. 
so need to check all the others case with all features..
btw for me if its jsut a visual glitch on one frame. we dont care. it s tool before all no ?

**Comment by aiekick** [comment]
yes please. your solution is working fine

**Comment by jvannugteren** [comment]
Ok done. See pull request.

**Comment by aiekick** [comment]
thanks you :)

**Comment by jvannugteren** [comment]
Thanks, problem solved. (=

**Comment by jvannugteren** [comment]
Unfortunately this issue has resurfaced. It can probably be easily fixed by commenting line 3897 in ImGuiFileDialog.cpp:
```
// return true; // needToBreakTheloop
```
Thanks.

**Comment by aiekick** [comment]
yes its possible i rewrote it a bit for the new picture system.

thanks

**Comment by aiekick** [comment]
fixed ! :)
