### ISSUE TITLE
Question - How to change the directory icon

### ISSUE THREAD

**Issue by KittoChanKC** [aiekick/ImGuiFileDialog#65]
I want to change the [Dir] to icon-font same as sample

I tried SetExtentionInfos but seems only can change the file icon

**Comment by aiekick** [comment]
yes you can change that i the custom config file
by ex like that : 
#define dirEntryString ICON_IGFD_FOLDER
you can check the sample app in master branch, for see how tis working

**Comment by KittoChanKC** [comment]
oh, I got it Thanks!

the library is easy to use
thank for your works :)
