### ISSUE TITLE
Larger Fonts Hide Buttons

### ISSUE THREAD

**Issue by ardenrasmussen** [aiekick/ImGuiFileDialog#7]
**Describe the bug**
The `Cancel` and `Ok` buttons do not fit on the window with larger fonts. I believe that it is due to the fixed number on line [719](https://github.com/aiekick/ImGuiFileDialog/blob/2f339ccf27be738924ca31fc724c8030741926c4/ImGuiFileDialog.cpp#L719) which sets the space available after the file list to 120 pixels. This should be scaled depending on the size of the font.

**To Reproduce**
1. Load a font with a font size greater than 15.
2. Open the File Dialog

**Expected behavior**
I would expect that the buttons are always visible no matter the font size and that the length of the file list is scaled to use less space. Although it is possible to reveal the buttons with the scroll bar, I believe that this behavior is undesirable.

**Comment by aiekick** [comment]
thanks for reporting the bug. its fixed now. :)
