### ISSUE TITLE
Double-click-to-open does not work under Directory Chooser mode.

### ISSUE THREAD

**Issue by xhsu** [aiekick/ImGuiFileDialog#73]
**Describe the bug**
The folder selection mode does not work.
According to the guide [here](https://github.com/aiekick/ImGuiFileDialog#directory-chooser-), the Directory Chooser should allow single-click for choosing folder and double-click for opening one.
But now the double-click-to-open is not working at all, the only thing I can do is choose one.

**To Reproduce**
- Use the exact example code.
- Use the latest ImGui with no Viewport or Docking.
- Using OpenGL 3 with GLFW.
- With freetype and stb.
- With ImGui config
> #define IMGUI_DISABLE_OBSOLETE_FUNCTIONS
> #define IMGUI_USE_STB_SPRINTF
> #define IMGUI_ENABLE_FREETYPE
- With ImGuiFileDialogConfig.h
> #define USE_STD_FILESYSTEM
> #define USE_EXPLORATION_BY_KEYS
> // this mapping by default is for GLFW but you can use another
> #include <GLFW/glfw3.h> 
> // Up key for explore to the top
> #define IGFD_KEY_UP GLFW_KEY_UP
> // Down key for explore to the bottom
> #define IGFD_KEY_DOWN GLFW_KEY_DOWN
> // Enter key for open directory
> #define IGFD_KEY_ENTER GLFW_KEY_ENTER
> // BackSpace for comming back to the last directory
> #define IGFD_KEY_BACKSPACE GLFW_KEY_BACKSPACE
- With Visual Studio 2022 and compiling option "/std:c++latest" (Hence C++20 or 23?)

**Expected behavior**
A clear double-clear can open a folder instead of selecting it.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
- Windows 10 21H1

**Smartphone (please complete the following information):**
 - None

**Additional context**

**Comment by aiekick** [comment]
Hello, 

thanks for letting me know there is a bug.

do you have the keyboard nav system activated ? (because the behavior is special in this mode and a bit bugged)

**Comment by xhsu** [comment]
Thank you for your reply.
I would test the Master branch once I back from work.

The problematic code is [here](https://github.com/xhsu/CZero-Editor/blob/master/Main.cpp), starting from Line 112, if you need more detail. I believe that apart from ```OpenDialog()``` versus ```OpenModal()``` there is no difference with your example.

**Comment by xhsu** [comment]
I fail to understand how am I supposed to compile and execute your Master branch on my computer, for it contains no .sln or .vcxproj file.

And I further tested the keyboard navigation part:
- The UpArrow and DownArrow to navigate will work despite the absence of ```USE_EXPLORATION_BY_KEYS``` macro.
- Backspace and Enter keys not working.
- Esc (default ImGui key to escape to parent wigid) causes an assert failure when USE_EXPLORATION_BY_KEYS exists.

**Comment by aiekick** [comment]
You just need to read the readme.md... all is explained

**Comment by xhsu** [comment]
Yes I have read it, all I do is copy the codes from [here](https://github.com/aiekick/ImGuiFileDialog/tree/master#simple-dialog-) and replace the ```OpenDialog()``` line with the counterpart from Directory Chooser section...

**Comment by aiekick** [comment]
i have tested you code in the master branch app and all is working as expected :

![image](https://user-images.githubusercontent.com/1434736/146983251-4d39c553-8c3c-4a0c-aefe-0d0c5094402b.png)

the demo :

![XzSQGBlTVJ](https://user-images.githubusercontent.com/1434736/146983440-1d50b74d-34cd-4d86-817e-4e502358de0f.gif)

**Comment by xhsu** [comment]
Thank you for your further investigation.
I tested the Master branch app, and it works just fine...
Sorry for the false alarm, I would dig into the code and see what I did wrong.

**Comment by aiekick** [comment]
Nice to hear.
Dont hesitate to come back on this thread il you think some  thing related to your bug and imguigiledialog can be improved in imguifiledialog.
Its a good point if imguifiledialog can be used easily in many behaviors.

Can i use your popup code ( similar) for the demo app in master branch. Its an interesting possible way, i would likke to show

**Comment by xhsu** [comment]
> Can i use your popup code ( similar) for the demo app in master branch. Its an interesting possible way, i would likke to show

Of course you can. It is my pleasure to help the open-source community.
