### ISSUE TITLE
Detached head or something in git

### ISSUE THREAD

**Issue by caxapexac** [aiekick/ImGuiFileDialog#75]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/33996246/147505651-5eb7a978-f01d-4264-b76a-dcc4fafe71cf.png)
Source code of file dialog lays somewhere not in master, thats not good at all

**Describe the solution you'd like**
Store source code in simple folder (so you won't need to use submodules to download source code of this widget)

**Comment by aiekick** [comment]
i do that because workfows of github is working only in master branch. 
i will change that when github will support other branchs.

btw if you have issue this is becausr you not read the readme.md..

**Comment by caxapexac** [comment]
Oh sorry skipped lib branch info in readme

But as I know github supports workflows/actions in any branch

**Comment by aiekick** [comment]
it was not the case one month ago

**Comment by aiekick** [comment]
Hello,

The lib is now in the master branch.

With time all happen 🤪

**Comment by caxapexac** [comment]
Finally!
Now I need to remember where have I used that library lol
