### ISSUE TITLE
SetFileStyle not working in Windows

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#79]
The `SetFileStyle` seems to have no effect when used in windows C++11 (so without std::filesystem). I'm using:
```
ImGuiFileDialog::Instance()->SetFileStyle(IGFD_FileStyleByExtention,".json", ImVec4(0.0039216f,0.8f,0.4000000f,1.0f), "\xef\x81\xb6");
```
but color doesn't change and the icon does not show up. I get no compile or runtime errors. In Linux the same line works fine.

**Comment by aiekick** [comment]
Are you sure you are suing it well ?
Can you show me the display code you are using for display the dialog ?
Are you sure about the filter ?
You can check the sample App for help by example..where this feature is working well

**Comment by jvannugteren** [comment]
Thanks for checking. In the mean while I checked OSX and it works fine there as well. So for my case only windows seems affected. I'm thinking maybe its related to win11? Its late here, I will try win10 tomorrow to confirm.

**Comment by aiekick** [comment]
ok thanks fro your support :) 

maybe a issue related to unicode when to string are compared ?

**Comment by jvannugteren** [comment]
There seem to be multiple instances. Must be some sort of linker problem.

**Comment by aiekick** [comment]
not sure to understand clearly.
can you precise it please ?

maybe can you test the sample app too

**Comment by jvannugteren** [comment]
Sure. Sorry I was almost more mumbling to myself there. I have figured out the problem, the singleton `ImGuiFileDialog::Instance()` was using a different `static FileDialog` in different parts of my code. So when I called `SetFileStyle`, it was pointing to a different instance, than when the file dialog was opened and used. The reason seems to be that the first was used in an executable and the second in a shared library linked to this executable. Apparently the msvc compiler has a slightly different behavior than the gcc compiler with respect to `static`. I solved the problem by not using the singleton, but instead making my own centralized `FileDialog` variable. If you agree I think we can close the issue as I do not see a solution to the different instances, when using multiple shared libraries, apart from what I just did.

**Comment by aiekick** [comment]
ah ok, good to here than the issue is not on the lib himself.

yes msvc is not working like gcc, a lot more permissive, and ignore many part of unused code. even a code who have compil issue. frequently discover issue with gcc than msvc ignore. so will add you issue to my check list because my main dev task is with msvc :)

thanks for you support btw :)

**Comment by jvannugteren** [comment]
Many thanks.
