### ISSUE TITLE
Wrong directory bug when using dialog a second time

### ISSUE THREAD

**Issue by RamiAwar** [aiekick/ImGuiFileDialog#8]
When I used the simple dialog example and selected a file, everything worked perfectly. When I opened the dialog again to select another file, I was sort of "stuck" in a directory, which is the "." vPath specified before on creation of the ImGuiFileDialog class, but none of the folders were clickable. Its like I was in the directory and could see everything but could not interact. When I clicked ".." however, I went up a directory from the previously chosen file, and not where I seemed to be, which is ".". 
For example, lets say I was in directory assets/.
We have:
assets/
  |---> textures
          | ----> image.png
  |---> test.txt

Let's say I opened the dialog and chose image.png. The next time I open the dialog, I see the following:
- . .
- textures
- test.txt

But they are both not clickable. 
Only thing clickable is ". .", and when I do click it, I find myself in directory assets, which means I was actually in textures the second time but it looked like I was already in assets.

A quick workaround I wrote that works perfectly is the following:
```
void ImGuiFileDialog::CloseDialog(const std::string & vKey)
{
	if (dlg_key == vKey)
	{
        ------> SetPath(m_CurrentPath);
		dlg_key.clear();
		m_ShowDialog = false;
	}
}
```

**Comment by aiekick** [comment]
thanks for report. I appreciate to not be alone on this project :)
i just comited the new version with yours fixs and the multiselection new feature.
let me know, if its ok now ?

**Comment by RamiAwar** [comment]
Its great, thanks!
