### ISSUE TITLE
FileDialog showing all formats

### ISSUE THREAD

**Issue by Ar-Ess** [aiekick/ImGuiFileDialog#81]
I am trying to create a file dialog filter such as "All Files".

Actually, I only have the option to set different types of formats such as ".wav, .mp3, .flac",
but I'd like to have a default one which shows all formats at once.

This is my FileDialog open code:

ImGuiFileDialog::Instance()->OpenDialog("ChooseFileDlgKey", "Choose an Audio File", ".wav,.mp3,.flac", ".");

**Comment by aiekick** [comment]
Just use thz filter ".*"

You can chzck the sample app for see what you can do Ith it

**Comment by Ar-Ess** [comment]
Thanks for the response! I already checked the sample app, but I might be blind that day ^^')

**Comment by Ar-Ess** [comment]
And, just to ask.
Using ".*" shows all files, but there is any way to quote that "all files" to "some files"?

Let me explain. As my example showed, I just want to search for .mp3, .flac, .wav files. Is there a way to filter and just show
tose formats??

Thanks!

**Comment by aiekick** [comment]
this use case is covered by the sample app and the doc.
see the [filter collections](https://github.com/aiekick/ImGuiFileDialog#filter-collections)

the onyl use case who is not possible at this moment, is if you need all files except some ones..
