### ISSUE TITLE
App crashes when clicking "Edit Path" button

### ISSUE THREAD

**Issue by ppelikan** [aiekick/ImGuiFileDialog#82]
**Describe the bug**
When pressing the "Edit Path" button, application crashes with following error:
```
ImGuiFileDialog: xyz/ImGuiFileDialog/3rdparty/imgui/imgui.cpp:7473: ImGuiKeyData* ImGui::GetKeyData(ImGuiKey): Assertion `key >= ImGuiKey_LegacyNativeKey_BEGIN && key < ImGuiKey_NamedKey_END' failed.
zsh: abort (core dumped)  xyz/ImGuiFileDialog/b/ImGuiFileDialog
```

**To Reproduce**
1. Build provided example (as described in README.md) and run `ImGuiFileDialog` executable
2. Click on "Open File Dialog"
3. Click button with pencil icon (tooltip says "Edit Path") OR right click any of the path buttons.
4. See app crash with error

**Expected behavior**
Obviously crash should not happen.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64, (5.15.19-1-MANJARO)
 - Version: newest `master` commit of ImGuiFileDialog `87cd5de`

**Additional context**
This also happens in my app, which uses the `Lib_Only` branch.

**Comment by aiekick** [comment]
i seen that, but i suspect its due to a recent change to the keymap in imgui. 
now we need to adapat backedn for declare keys

i have the fix when the IMGUI_DISABLE_OBSOLETE_KEYIO is undefined
but not when its defined, and its needed since this the forward behavior

**Comment by aiekick** [comment]
fixed on my side. like said you need to adpat your backend to the new ImGuiKey feature or using the define IMGUI_DISABLE_OBSOLETE_KEYIO for keep the old way. the rest is on ImGui Side.

can you confirm its working for you too ?

**Comment by ppelikan** [comment]
I can confirm, problem is fixed.
However, clicking the "Edit Path" button for the second time, does not switch back to the the path buttons. But that's probably another thing, not related to this bug.

**Comment by aiekick** [comment]
indeed, because im using escape key each time.

but if make sense for you to click again for hide it, i will do that :)
maybe make sense for others :)

**Comment by aiekick** [comment]
done in the last commit : 6852dcd4e585c9c07cb93491ab88731f3d3ac7f3

**Comment by ppelikan** [comment]
Thank you very much for your work and for this project! :)
