### ISSUE TITLE
Extra slash next to root in linux

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#84]
With the newly added slashes in the file-path. I'm getting an additional slash next to the root slash in Linux. I think it shouldn't be there. There is no problem in windows.

See screenshot:
![image](https://user-images.githubusercontent.com/78733220/155761041-d7c870f4-7eed-448e-93aa-5120cf8be2ef.png)

Would it be possible to make the newly added slashes optional with a compile flag? They take up quite a bit of space when using longer paths. Many thanks.

**Comment by aiekick** [comment]
haha yes , good point :)

yes i can do that np :)

the slash feature was to quickly select another dir when you click on it :)

**Comment by jvannugteren** [comment]
Ye another solution could be to reduce the spacing by setting `ImGui::SameLine(0,0)` on both lines 2391 and 2413. For optional I think you can simply put an #ifdef over 2389 to 2414.

**Comment by aiekick** [comment]
fixed. disabled by default by the define USE_QUICK_PATH_SELECT

yes its intersting to add a define for that :) thanks for the idea :)

**Comment by jvannugteren** [comment]
Thanks for fast fixes. I have tested with and without define in both windows and linux and all works correctly now. The defines are also much appreciated. (=

**Comment by jvannugteren** [comment]
Hi in the master branch the slashes now appear even when not setting USE_QUICK_PATH_SELECT. This feature was dropped about a month ago. Can you re-enable it?

**Comment by aiekick** [comment]
hi, 
now you need to use the flag ImGuiFileDialogFlags_DisableQuickPathSelection 
i will remove many define in the same way in few times
