### ISSUE TITLE
Segfault on manually editing the path

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#85]
Sorry for opening two issues on the same day. I found that if you click the E to edit the path and then type in something nonsensical or make a typo in the path. The GUI will crash with a segfault after hitting enter. Thanks. 

![image](https://user-images.githubusercontent.com/78733220/155811654-5530b31e-6de7-48f8-bd86-c24d80466750.png)

**Comment by aiekick** [comment]
can you precise your settings, because i tried to reproduce the bug, but nothing is crashing on my side.

**Comment by aiekick** [comment]
are you sure your issue is not the same as here :  #82 ?

do you test the sample app ?

there is a big change in last imgui about keymap now.

**Comment by jvannugteren** [comment]
Ok, nice. Reproduction is usually the tricky part. It probably needs to check somewhere that the path inserted is actually valid or something. I'm not sure but the error might be triggered as well when you set a non-existing path during `OpenModal`.

**Comment by aiekick** [comment]
fixed i guess, can you check ?

**Comment by jvannugteren** [comment]
I checked and the fix works at least in Linux. Its fine as is now. Not hard crashing is the most important. (=

Another suggestion. Feel free to ignore. Maybe you can turn std::filesystem into a macro such that I have the option to change it to boost::filesystem as well (their API's should be identical). I'm using this for the rest of the application.

**Comment by aiekick** [comment]
yep why not, can be dangerous, if the interface is not the same or guys are using another custom file system.
or can just use a IGFS FX interface of something

**Comment by jvannugteren** [comment]
Hehe, I just tried using find and replace. I agree it is dangerous. I found only two functions really missing from `boost::filesystem`: `is_symlink` and `is_directory`. For now I'll just continue with dirent then.

**Comment by aiekick** [comment]
yep i cant go in this way :)

**Comment by aiekick** [comment]
Hello,
i have added a FileSystem interface. you can now use your own FileSystem.
check the DemoApp who show how to use this feature with bool::filesystem
