### ISSUE TITLE
Does not compile without bookmarks enabled

### ISSUE THREAD

**Issue by Lyderik** [aiekick/ImGuiFileDialog#86]
In OmGuiFileDialog.cpp on line 3974, the flag ```ImGuiFileDialogFlags_DisableBookmarkMode``` is referenced outside the #ifdef and #ifndef directives for ```USE_BOOKMARK ```
``` c++
if (!(prFileDialogInternal.puDLGflags & ImGuiFileDialogFlags_DisableBookmarkMode) ||
	!(prFileDialogInternal.puDLGflags & ImGuiFileDialogFlags_DisableCreateDirectoryButton))
{
```
This cause it to not compile, it compiles with USE_BOOKMARK enabled.

**Comment by aiekick** [comment]
arf, thanks

**Comment by aiekick** [comment]
just fixed. sorry or this basic issue haha :)
