### ISSUE TITLE
Multiple file dialogs with different filters conflict

### ISSUE THREAD

**Issue by RamiAwar** [aiekick/ImGuiFileDialog#9]
I created two file dialogs, one for .ext1 and another for .ext2. When I choose my first file using dialog 1 with filter .ext1, everything works perfectly. But when I try using the second dialog, it still filters according to .ext1 instead of using .ext2. 

A way around this is triggering the combo box for choosing filters, which shows the right filters, and just pressing on .ext2 for example. This refreshes the filters somehow. I still don't know how to fix this in code, as I don't understand the filtering much.

This should be easy to fix since using the combo box and selecting the right extensions results in the expected behavior, but I'm not as familiar with the library. Tu peux m'aider? @aiekick 

[EDIT]
This code workaround works, I added to ALL OpenDialog constructors :
```
void ImGuiFileDialog::OpenDialog(const std::string & vKey, const char* vName, const char* vFilters,
	const std::string & vPath, const std::string & vDefaultFileName,
	const std::function<void(std::string, bool*)> & vOptionsPane, size_t vOptionsPaneWidth, const std::string & vUserString)
{
	if (m_ShowDialog) // si deja ouvert on ne fou pas la merde en voulant en ecrire une autre
		return;

	dlg_key = vKey;
	dlg_name = std::string(vName);
	dlg_filters = vFilters;
	dlg_path = vPath;
	dlg_defaultFileName = vDefaultFileName;
	dlg_optionsPane = std::move(vOptionsPane);
	dlg_userString = vUserString;
	dlg_optionsPaneWidth = vOptionsPaneWidth;

	dlg_defaultExt = "";

	+int itemIdx = 0;
	+const char* p = dlg_filters;
	+while (*p)
	+{
	+	if (FilterIndex == itemIdx)
	+	{
	+		m_SelectedExt = std::string(p);
	+		break;
	+	}
	+	p += strlen(p) + 1;
	+	itemIdx++;
	+}

	m_ShowDialog = true;
}
```

I copied this code from comboClick in the filter combo box display in FileDialog.

**Comment by aiekick** [comment]
i work on a fix for the next release. 
you can just clear m_SelectedExt, and he will be reconstructed with the first filter

**Comment by RamiAwar** [comment]
Yes that's a neater solution, thanks!
