### ISSUE TITLE
Need case sensitive option for file extension filter

### ISSUE THREAD

**Issue by ilovexyz** [aiekick/ImGuiFileDialog#91]
**Is your feature request related to a problem? Please describe.**
I want to filter my stl files, using 

```
const char* filters = "All Model files{.stl,.ply},.stl,.ply";
...
ImGuiFileDialog::Instance()->OpenModal("ImportNewModel", buf, filters, m_cur_data_dir);
```
bus sometimes, 3D modeling softwares export stl files with extension of upper case, `test.STL` for example. In this case, the file will be filtered and not shown in the dialog. 

The same problems exists for JPG/jpg files.

**Describe the solution you'd like**
Add a case sensitive option, so i can choose whether the extension is case sensitive or not.

I can specify both lower case and upper case extension in the code, but i think it's not user friendly.

**Comment by aiekick** [comment]
Hello,
Thanks. Yep its a good feature to add.

Will work on it when i have time. Not before saturday sorry

**Comment by ilovexyz** [comment]
> 

great, thanks!

**Comment by aiekick** [comment]
added !

you can use this flag 'ImGuiFileDialogFlags_CaseInsensitiveExtention' when you call the open functions

```
by ex :
if the flag ImGuiFileDialogFlags_CaseInsensitiveExtention is used
with filters like .jpg or .Jpg or .JPG
all files with extentions by ex : .jpg and .JPG will be displayed
```
you can check the doc and the sample app 

can you test and say if its ok for you ?

**Comment by ilovexyz** [comment]
> added !
> 
> you can use this flag 'ImGuiFileDialogFlags_CaseInsensitiveExtention' when you call the open functions
> 
> ```
> by ex :
> if the flag ImGuiFileDialogFlags_CaseInsensitiveExtention is used
> with filters like .jpg or .Jpg or .JPG
> all files with extentions by ex : .jpg and .JPG will be displayed
> ```
> 
> you can check the doc and the sample app
> 
> can you test and say if its ok for you ?

yes, that worked, thanks!
<img width="308" alt="snapshot" src="https://user-images.githubusercontent.com/18619226/162578972-0d3994d2-b5e7-429e-ac4b-ce67a572f1ba.png">
