### ISSUE TITLE
Compile error related to filetype.content

### ISSUE THREAD

**Issue by jvannugteren** [aiekick/ImGuiFileDialog#92]
In the latest version(s) I'm getting the following compile error:
```
ImGuiFileDialog.cpp:1535:58: error: ‘class IGFD::FileType’ has no member named ‘content’; did you mean ‘IGFD::FileType::ContentType IGFD::FileType::m_Content’? (not accessible from this context)
```
This error probably only shows when compiling with Dirent. Its likely something simple but if not let me know and I'll find you more info.

Thanks for checking.

**Comment by aiekick** [comment]
hello,
yes we are working on it.

its better to use only the released version

**Comment by jvannugteren** [comment]
Thanks. You're right, I'll switch to release.
