### ISSUE TITLE
Crash by unhandled exception while iterating a directory without permission

### ISSUE THREAD

**Issue by enelija** [aiekick/ImGuiFileDialog#94]
Hello, 

**Description**
Trying to enter a directory with insufficient permission crashes the application due to an unhandled exception, thrown by the std filesystem directory_iterator (USE_STD_FILESYSTEM enabled).

**Reproduce**
Run an application, using the ImGuiFileDialog browser and try accessing C:\System Volume Information or any other directory with no permission for the currently logged in user on Windows for example.

**System**
Windows 10, ImGui with Vulkan, ImGuiFileDialog branch Lib_Only commit 531596a8f33fae9343211836614575a3149baf23

**Comment by aiekick** [comment]
its fixed on my side, can you check that ?

**Comment by enelija** [comment]
Thanks for the fast fix!
