### ISSUE TITLE
Error when creating directories that contains spaces.

### ISSUE THREAD

**Issue by AdrianoDiDio** [aiekick/ImGuiFileDialog#96]
**Describe the bug**
I was trying to use the built-in feature of the dialog to create a new directory in Linux and I've noticed that mkdir (used in the library) created the wrong directories due to the spaces that were in the file path.
I'm not sure if CreateWindow  function in Windows or std::fs::create_directory handles spaces correctly but at least on Linux and EmScripten you need to add double-quotes to the directory string in order to parse the spaces correctly.
For example in the linux code:
`
snprintf(buffer, PATH_MAX, "mkdir -p \"%s\"", name.c_str());
				`
Although I'm not sure if this is the right solution or if it would be better to use (at least on Linux) the function mkdir to create recursively the directories as seen in this post on StackOverflow:
[https://stackoverflow.com/questions/2336242/recursive-mkdir-system-call-on-unix](https://stackoverflow.com/questions/2336242/recursive-mkdir-system-call-on-unix)

**Comment by aiekick** [comment]
Hello,

thanks for the bug. its interesting. 

its wierd to me to have spaces in directory names on linux but ok :)

**Comment by aiekick** [comment]
Hello,

sorry for the laste reply, (i forgot the issue :))

i've tested you fix, and its working very well, so tis commited :)

Thanks
